### ISSUE TITLE
시스템 운영 중 분석 이벤트 검출 중지

### ISSUE THREAD

**Issue by TaeHoon-SNU** [snuailab/autocare_issue_reporter#11]
[Pre-condition & Test Data]
웹페이지 http://{IP address}:8000/frontend/console/와 MX-Client(VIVEex) 실행

[Environment]
Mx-Client(VIVEex) Version: 4.2.0.32843, Ubuntu 20.04, autocare_docker S/W Version : 11/12 배포 S/W

[Steps to reproduce]
1. MX 플러그인 활성화 → 영상 아이템 표시의 객체 활성화 → 분석 이벤트 검출 시작(21-11-19 19:05) → 분석 이벤트 검출 중지(21-11-20 12:35) → 증상 확인(21-11-22 08:59)
2. docker-compose restart 하여 복구

[Expect result]
1. 플러그인 활성화 후 시스템 운영 중 분석 이벤트가 지속적으로 검출되어야 한다
2. 시스템 복구 후 분석 이벤트가 검출되고 영상에 박스가 나타나야 된다

[Actual result]
1. 시스템 운영 중 분석 이벤트 검출 중지
2. 시스템 복구 후 분석 이벤트가 검출되나 영상에 박스가 안나타남

[Frequency]
Checking

[Severity/Priority]
Critical

1. 시스템 운영 중 분석 이벤트 검출 중지

분석 이벤트 검출 시작 docker-compose logs 정보
[36mautocare_ax_1  |[0m 2021-11-19 19:05:26,711 [DEBUG] multipart.multipart: Calling on_part_data with data[0:1]
        . . .
[32mautocare_mx_1  |[0m [device_agent] check trackInfo trackInfo.size() : 0
[32mautocare_mx_1  |[0m [rtp @ 0x7f4adc009f60] Using AVStream.codec.time_base as a timebase hint to the muxer is deprecated. Set AVStream.time_base instead.
[32mautocare_mx_1  |[0m [rtp @ 0x7f4adc009f60] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[32mautocare_mx_1  |[0m [rtp @ 0x7f4adc268260] Using AVStream.codec.time_base as a timebase hint to the muxer is deprecated. Set AVStream.time_base instead.
[32mautocare_mx_1  |[0m [rtp @ 0x7f4adc268260] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[32mautocare_mx_1  |[0m [device_agent] check trackInfo trackInfo.size() : 0
[32mautocare_mx_1  |[0m [device_agent] check trackInfo trackInfo.size() : 0
[32mautocare_mx_1  |[0m [device_agent] check trackInfo trackInfo.size() : 0
[32mautocare_mx_1  |[0m [device_agent] inference id : [device_agent] inference id : [device_agent] inference id : -1{"cmd": "Start", "inference_id": 2, "result": "Success", "app": "1e79d740-4298-4325-b51d-5bfc1b0c9e07", "stream": "e658e4d0-7815-a81f-995a-469ecef0312c", "model": "4e3c09d4-40a8-4b7f-8830-d14a811cf7b9"}-1{"cmd": "Start", "inference_id": 2, "result": "Success", "app": "1e79d740-4298-4325-b51d-5bfc1b0c9e07", "stream": "e658e4d0-7815-a81f-995a-469ecef0312c", "model": "4e3c09d4-40a8-4b7f-8830-d14a811cf7b9"}
[32mautocare_mx_1  |[0m 
[32mautocare_mx_1  |[0m -1{"cmd": "Start", "inference_id": 2, "result": "Success", "app": "1e79d740-4298-4325-b51d-5bfc1b0c9e07", "stream": "e658e4d0-7815-a81f-995a-469ecef0312c", "model": "4e3c09d4-40a8-4b7f-8830-d14a811cf7b9"}[device_agent] inference id : 1{"cmd": "Start", "inference_id": 2, "result": "Success", "app": "1e79d740-4298-4325-b51d-5bfc1b0c9e07", "stream": "e658e4d0-7815-a81f-995a-469ecef0312c", "model": "4e3c09d4-40a8-4b7f-8830-d14a811cf7b9"}[device_agent] Success to assign dx to channel
[32mautocare_mx_1  |[0m 
[32mautocare_mx_1  |[0m 
[32mautocare_mx_1  |[0m [rtp @ 0x7f4a38009760] Using AVStream.codec.time_base as a timebase hint to the muxer is deprecated. Set AVStream.time_base instead.
[32mautocare_mx_1  |[0m [rtp @ 0x7f4a38009760] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[32mautocare_mx_1  |[0m [rtp @ 0x7f4a38267d00] Using AVStream.codec.time_base as a timebase hint to the muxer is deprecated. Set AVStream.time_base instead.
[32mautocare_mx_1  |[0m [rtp @ 0x7f4a38267d00] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[32mautocare_mx_1  |[0m [rtp @ 0x7f4a6415b600] Using AVStream.codec.time_base as a timebase hint to the muxer is deprecated. Set AVStream.time_base instead.
[32mautocare_mx_1  |[0m [rtp @ 0x7f4a6415b600] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[32mautocare_mx_1  |[0m [device_agent] inference id : [device_agent] inference id : 2{"cmd": "Start", "inference_id": 3, "result": "Success", "app": "1e79d740-4298-4325-b51d-5bfc1b0c9e07", "stream": "92f2c5c4-aac2-b6dd-e592-b2722d37636c", "model": "4e3c09d4-40a8-4b7f-8830-d14a811cf7b9"}
[32mautocare_mx_1  |[0m [device_agent] 1inference id : -1{"cmd": "Start", "inference_id": 3, "result": "Success", "app": "1e79d740-4298-4325-b51d-5bfc1b0c9e07", "stream": "92f2c5c4-aac2-b6dd-e592-b2722d37636c", "model": "4e3c09d4-40a8-4b7f-8830-d14a811cf7b9"}{"cmd": "Start", "inference_id": 3, "result": "Success", "app": "1e79d740-4298-4325-b51d-5bfc1b0c9e07", "stream": "92f2c5c4-aac2-b6dd-e592-b2722d37636c", "model": "4e3c09d4-40a8-4b7f-8830-d14a811cf7b9"}[device_agent] inference id : -1{"cmd": "Start", "inference_id": 3, "result": "Success", "app": "1e79d740-4298-4325-b51d-5bfc1b0c9e07", "stream": "92f2c5c4-aac2-b6dd-e592-b2722d37636c", "model": "4e3c09d4-40a8-4b7f-8830-d14a811cf7b9"}
[32mautocare_mx_1  |[0m 
[32mautocare_mx_1  |[0m 
[32mautocare_mx_1  |[0m [device_agent] Success to assign dx to channel
[32mautocare_mx_1  |[0m [rtp @ 0x7f4a642683a0] Using AVStream.codec.time_base as a timebase hint to the muxer is deprecated. Set AVStream.time_base instead.
[32mautocare_mx_1  |[0m [rtp @ 0x7f4a642683a0] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[32mautocare_mx_1  |[0m [device_agent] check trackInfo trackInfo.size() : 133
[32mautocare_mx_1  |[0m [device_agent] (00000000-0000-0000-0000-000000000013, Car, 1637316504435268
[32mautocare_mx_1  |[0m [device_agent] (00000000-0000-0000-0000-000000000006, Car, 1637316504013816

분석 이벤트 검출 중지 docker-compose logs 정보
[32mautocare_mx_1  |[0m [device_agent] (00000000-0000-0000-0000-000000099260, Person, 1637379335889672
[32mautocare_mx_1  |[0m [device_agent] check trackInfo trackInfo.size() : 0
[32mautocare_mx_1  |[0m [device_agent] check trackInfo trackInfo.size() : 18446744073709551614
[32mautocare_mx_1  |[0m Launching mediaserver-bin
[32mautocare_mx_1  |[0m nx_utils.ini (absent) To fill in defaults, touch /root/.config/nx_ini/nx_utils.ini
[32mautocare_mx_1  |[0m vms_server_plugins.ini (absent) To fill in defaults, touch /root/.config/nx_ini/vms_server_plugins.ini
[32mautocare_mx_1  |[0m 2021-11-20 12:35:50.655 1016341 WARNING QnLongRunnable(0x55d8650d4340): QnLongRunnablePool instance does not exist, lifetime of this runnable will not be tracked.
[32mautocare_mx_1  |[0m 2021-11-20 12:35:50.704 1016341 WARNING QnLongRunnable(0x55d8650db4e0): QnLongRunnablePool instance does not exist, lifetime of this runnable will not be tracked.
[32mautocare_mx_1  |[0m 2021-11-20 12:35:50.706 1016341 WARNING nx::utils::Settings(0x55d8650df080): Unknown option: NORMAL_SCAN_ARCHIVE_FROM
[32mautocare_mx_1  |[0m 2021-11-20 12:35:50.706 1016341 WARNING nx::utils::Settings(0x55d8650df080): Unknown option: cloudHost
[32mautocare_mx_1  |[0m 2021-11-20 12:35:50.706 1016341 WARNING nx::utils::Settings(0x55d8650df080): Unknown option: isConnectedToCloud
[32mautocare_mx_1  |[0m 2021-11-20 12:35:50.706 1016341 WARNING nx::utils::Settings(0x55d8650df080): Unknown option: logFile
[32mautocare_mx_1  |[0m 2021-11-20 12:35:50.707 1016341 WARNING nx::utils::Settings(0x55d8650df080): Unknown option: prevSystemName
[32mautocare_mx_1  |[0m 2021-11-20 12:35:50.707 1016341 WARNING nx::utils::Settings(0x55d8650df080): Unknown option: storedMac
[32mautocare_mx_1  |[0m 2021-11-20 12:35:50.707 1016341 WARNING nx::utils::Settings(0x55d8650df080): Unknown option: systemName
[32mautocare_mx_1  |[0m vms_server_raid_event.ini (absent) To fill in defaults, touch /root/.config/nx_ini/vms_server_raid_event.ini
[32mautocare_mx_1  |[0m nx_network.ini (absent) To fill in defaults, touch /root/.config/nx_ini/nx_network.ini
[32mautocare_mx_1  |[0m 2021-11-20 12:35:50.729 1016362 WARNING nx::utils::Settings(0x7f4004004590): Unknown option: NORMAL_SCAN_ARCHIVE_FROM
[32mautocare_mx_1  |[0m 2021-11-20 12:35:50.729 1016362 WARNING nx::utils::Settings(0x7f4004004590): Unknown option: cloudHost
[32mautocare_mx_1  |[0m 2021-11-20 12:35:50.729 1016362 WARNING nx::utils::Settings(0x7f4004004590): Unknown option: isConnectedToCloud
[32mautocare_mx_1  |[0m 2021-11-20 12:35:50.729 1016362 WARNING nx::utils::Settings(0x7f4004004590): Unknown option: logFile
[32mautocare_mx_1  |[0m 2021-11-20 12:35:50.729 1016362 WARNING nx::utils::Settings(0x7f4004004590): Unknown option: prevSystemName
[32mautocare_mx_1  |[0m 2021-11-20 12:35:50.729 1016362 WARNING nx::utils::Settings(0x7f4004004590): Unknown option: storedMac
[32mautocare_mx_1  |[0m 2021-11-20 12:35:50.729 1016362 WARNING nx::utils::Settings(0x7f4004004590): Unknown option: systemName
[32mautocare_mx_1  |[0m nx::utils::log::File(0x7f4004011330): /opt/viveex/mediaserver/var/log/log_file.log
[32mautocare_mx_1  |[0m open '/dev/poe' 66 --> 0
[32mautocare_mx_1  |[0m server_ptz.ini (absent) To fill in defaults, touch /root/.config/nx_ini/server_ptz.ini
[32mautocare_mx_1  |[0m nx_vms_server.ini (absent) To fill in defaults, touch /root/.config/nx_ini/nx_vms_server.ini
[32mautocare_mx_1  |[0m [plugin] Created autocare_pigcare_plugin[0x7f4004076b80]
[32mautocare_mx_1  |[0m autocare_plugin.ini [/root/.config/nx_ini/autocare_plugin.ini]

[ax.log](https://github.com/snuailab/autocare_issue_reporter/files/7577631/ax.log)
[hw_log.log](https://github.com/snuailab/autocare_issue_reporter/files/7577632/hw_log.log)
[log_file.log](https://github.com/snuailab/autocare_issue_reporter/files/7577633/log_file.log)

2. 시스템 복구 후 분석 이벤트가 검출되나 영상에 박스가 안나타남

![K-233](https://user-images.githubusercontent.com/93699320/142790126-5f032d1b-56bf-42ec-a511-ecc8be7e9aa5.png)
![K-234](https://user-images.githubusercontent.com/93699320/142790128-e58a50a2-700f-4c34-a917-8a78179f41f2.png)

https://user-images.githubusercontent.com/93699320/142791548-e2acbaa4-2f5f-4592-b1e6-8015c5edb8d6.mp4

**Comment by jaeminjeon-snuailab** [comment]
'시스템 분석 이벤트 검출 중지'란 의미는 autocare 시스템이 동작하던 중에 비정상적으로 동작을 멈췄다는 의미인가요?

**Comment by TaeHoon-SNU** [comment]
실시간으로 확인한 부분은 아닙니다.
금일 출근하여 분석 이벤트 검출이 안되는 증상을 확인했습니다.(21-11-22 08:59)
로그 확인 시 분석 이벤트 검출 중지되었습니다.(21-11-20 12:35)

**Comment by jaeminjeon-snuailab** [comment]
넵 알겠습니다. 확인해보겠습니다.
그리고 로그 시스템의 로그 파일 분할하여 저장하는 부분과 타임존 같은 경우에는 수정하여서 이번 주 배포 시에 적용될 예정입니다.

**Comment by jeongho2** [comment]
해당 문제는 차후 eternals release에 반영될 예정입니다.
