### ISSUE TITLE
멀티(외부) DX 검색 불가

### ISSUE THREAD

**Issue by TaeHoon-SNU** [snuailab/autocare_issue_reporter#12]
[Pre-condition & Test Data]
웹페이지 http://{IP address}:8000/frontend/console/

[Environment]
Mx-Client(VIVEex) Version: 4.2.0.32843, Ubuntu 20.04, autocare_docker S/W Version : 11/12 배포 S/W

[Steps to reproduce]
1.멀티 DX 검색 불가(A장비 검색 가능, B장비 검색 불가)
A 장비(192.168.0.53) : AX, DX, MX 설치
 → docker-compose up -d
B 장비(192.168.0.61) : DX만 설치(dx docker 내부에서 dx.ini 파일 수정
 → docker-compose.yml 파일 편집(ax와 mx 주석 처리)
 → docker-compose up -d
 → docker exec -it autocare_docker_autocare_dx_1 /bin/bash 접속
 → vi config/dx.ini 수정(uuid : 끝자리 1 -> 5 변경, uri : nats://localhost:4222 -> nats://192.168.0.53:4222 변경)
 → docker-compose restart
AX Overview 설정 → 모델 등록 → Discover new DX 클릭

2.외부 DX 검색 불가(B장비 검색 불가)
A 장비(192.168.0.53) : AX, DX, MX 설치
 → docker-compose.yml 파일 편집(dx 주석 처리)
 → docker-compose up -d
B 장비(192.168.0.61) : DX만 설치(dx docker 내부에서 dx.ini 파일 수정
 → docker-compose.yml 파일 편집(ax와 mx 주석 처리)
 → docker-compose up -d
 → docker exec -it autocare_docker_autocare_dx_1 /bin/bash 접속
 → vi config/dx.ini 수정(uri : nats://localhost:4222 -> nats://192.168.0.53:4222 변경)
 → docker-compose restart
AX Overview 설정 → 모델 등록 → Discover new DX 클릭

[Expect result]
1.멀티 DX 검색(A장비 검색 가능, B장비 검색 가능)이 가능해야 한다
2.외부 DX 검색이 가능해야 한다

[Actual result]
1.멀티 DX 검색 불가(A장비 검색 가능, B장비 검색 불가)
2.외부 DX 검색 불가(B장비 검색 가능)

[Frequency]
Alway

[Severity/Priority]
Critical

[멀티(외부) DX 검색 불가.zip](https://github.com/snuailab/autocare_issue_reporter/files/7578768/DX.zip)

![Discover new DX 기능 사용 불가](https://user-images.githubusercontent.com/93699320/142816948-b9571af9-bf82-4c00-893f-f2d310aac9c8.JPG)

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/93699320/142816959-1a707f9d-0942-48dc-90c0-4a6e95812ab0.png)

**Comment by jaypark-snuailab** [comment]
11/24 배포 버전에서 수정됨.

**Comment by TaeHoon-SNU** [comment]
검색은 가능하나 UUID를 수동으로 변경 필요
