### ISSUE TITLE
AX(localhost:8000/frontend/console/dx)에서 재실행 버튼 오류

### ISSUE THREAD

**Issue by mingeolyoo** [snuailab/autocare_issue_reporter#14]
[Pre-condition & Test Data]
웹페이지 http://{IP address}:8000/frontend/console/와 MX-Client(VIVEex) 실행

[Environment]
Mx-Client(VIVEex) Version: 4.2.0.32843, Ubuntu 18.04.6 LTS, autocare_docker S/W Version : 11/12 배포 S/W

[Steps to reproduce]
왼쪽 메뉴 리스트에서 DXs 메뉴 클릭 -> dx의 재실행 버튼 클릭

[Expect result]
DX 재실행(DX 중지됨) 버튼 클릭시 Mx-Client(VIVEex)에서 객체 검출되지 않아야 한다.

[Actual result]
DX 재실행(DX 중지됨) 버튼 클릭시 Mx-Client(VIVEex)에서 객체 검출됨

[Frequency]
Alway

[Severity/Priority]
Critical

[log.zip](https://github.com/snuailab/autocare_issue_reporter/files/7585847/log.zip)

![restart](https://user-images.githubusercontent.com/93703111/142971533-c96b60cf-83a9-4ac3-b43a-ec708e1822f5.JPG)

https://user-images.githubusercontent.com/93703111/142972369-4e52d143-0b06-4ca7-866d-073ed71dff43.mp4

**Comment by jaeminjeon-snuailab** [comment]
DX 재실행 버튼의 경우 DX를 중단했다가 기존의 설정으로 다시 파이프라인을 구축하여 실행하기 때문에 잠시 중단되었다가 분석이 재실행 되는 것이 정상입니다. 만약 DX를 중단하고자 하신다면 중지 버튼을 누르시면 됩니다.
해당 이슈는 resolve 처리 하겠습니다.
