### ISSUE TITLE
로그가 일자 또는 시간 별로 압축 및 저장되지 않고 1개의 파일로 저장

### ISSUE THREAD

**Issue by TaeHoon-SNU** [snuailab/autocare_issue_reporter#15]
[Pre-condition & Test Data]
MX-Server(VIVEex)

[Environment]
Ubuntu 20.04, autocare_docker S/W Version : 11/12 배포 S/W

[Steps to reproduce]
1. MX 로그
docker exec -it autocare_docker_autocare_mx_1 /bin/bash → cd /config/var/log → ls -al → hw_log.log, log_file.log 한 개의 파일로 저장
2. AX 로그
docker exec -it autocare_docker_autocare_ax_1 /bin/bash → cd /opt/autocare/autocare_ax → ls -al → ax.log 한 개의 파일로 저장
3. DX 로그
docker exec -it autocare_docker_autocare_dx_1 /bin/bash → cd opt/autocare/dx → ls -al → dx.log(30GB 이상) 한 개의 파일로 저장

[Expect result]
로그가 일자 또는 시간 별로 압축 및 저장되어야 한다

[Actual result]
로그가 일자 또는 시간 별로 압축 및 저장되지 않고 1개의 파일로 저장
DX 로그가 1일 미만  30GB이상 저장되어 오픈 또는 내용 확인이 어려움

[Frequency]
Allway

[Severity/Priority]
Major

![로그가 일자 또는 시간 별로 압축 및 저장되지 않고 1개의 파일로 저장](https://user-images.githubusercontent.com/93699320/142973975-f0c797ac-449b-4c22-8fda-efcece68582f.JPG)

**Comment by jaypark-snuailab** [comment]
11/24 버전에서 수정.

**Comment by TaeHoon-SNU** [comment]
MX 로그는 한 개의 파일로 저장
DX 로그는 로그 저장 시간 너무 짧음(약15분)
 - 저장 기간 연장 및 압축 필요

**Comment by TaeHoon-SNU** [comment]
MX 로그는 한 개의 파일로 저장

**Comment by jeongho2** [comment]
Mx Log는 Mx Client - 이벤트 로그(ctrl+L)에서 일반 이벤트로 필터링 설정을 하면 확인할 수 있습니다. 

Mx Log 파일은 Nx kit의 기능입니다.

/mnt/mx_volume/config/nx_ini/mediaserver-bin_stderr.log, /mnt/mx_volume/config/nx_ini/mediaserver-bin_stdout.log 에서 로그를 확인할 수 있고, Mx Server가 시작되면 이러한 파일이 있는지 여부를 확인합니다. 이들 중 하나라도 존재하는 경우 로그를 해당 파일로 리디렉션합니다. 프로세스가 시작될 때마다 파일이 다시 작성됩니다.
