### ISSUE TITLE
dx 시스템의 시간이 OS 시간과 차이 발생

### ISSUE THREAD

**Issue by TaeHoon-SNU** [snuailab/autocare_issue_reporter#17]
[Pre-condition & Test Data]
MX-Server(VIVEex)

[Environment]
Ubuntu 20.04, autocare_docker S/W Version : 11/12 배포 S/W

[Steps to reproduce]
1. MX 시간
docker exec -it autocare_docker_autocare_mx_1 /bin/bash → date
2. AX 시간
docker exec -it autocare_docker_autocare_ax_1 /bin/bash → date
3. DX 시간
docker exec -it autocare_docker_autocare_dx_1 /bin/bash → date

[Expect result]
각 docker 시스템의 시간이 OS 시간과 일치해야 한다

[Actual result]
dx 시스템의 시간이 OS 시간과 차이 발생

[Frequency]
Allway

[Severity/Priority]
Mino

![dx 시스템의 시간이 OS 시간과 차이 발생](https://user-images.githubusercontent.com/93699320/142974948-ef8e2f7c-6862-4ed0-a4ed-21eb574fec4d.JPG)
r

**Comment by jaeminjeon-snuailab** [comment]
해당 이슈는 DX의 Dockerfile에 Timezone을 환경변수로 추가하여 해결하였습니다. 금일 해결된 버전으로 배포될 예정입니다.
