### ISSUE TITLE
Overview에서 Default 모델이 선택은 되나 업데이트 불가

### ISSUE THREAD

**Issue by TaeHoon-SNU** [snuailab/autocare_issue_reporter#18]
[Pre-condition & Test Data]
웹페이지 실행 http://{IP address}:8000/frontend/console/

[Environment]
Ubuntu 20.04, autocare_docker S/W Version : 11/12 배포 S/W

[Steps to reproduce]
왼쪽 메뉴 리스트에서 Overview 메뉴 클릭→Default 모델 선택 후 CREAT(UPDATE) 클릭

[Expect result]
Overview에서 Default 모델이 선택 및 저장되어야 한다

[Actual result]
Overview에서 Default 모델이 선택은 되나 업데이트 불가

[Frequency]
Allway

[Severity/Priority]
Minor

**Comment by jaypark-snuailab** [comment]
이전 UI 문제로 11/24 배포 UI에서 개선.
