### ISSUE TITLE
DXs의 DX 상태와 DX 상세 정보의 Stats의 상태 표기 오류

### ISSUE THREAD

**Issue by TaeHoon-SNU** [snuailab/autocare_issue_reporter#2]
[Pre-condition & Test Data]
웹페이지 실행 http://{IP address}:8000/frontend/console/
[Environment]
Ubuntu 20.04, autocare_docker S/W Version : 11/04 배포 S/W
[Steps to reproduce]
왼쪽 메뉴 리스트에서 Dxs 메뉴 클릭 → 상세 정보를 확인할 DX Name의 DX 클릭
[Expect result]
DX의 상세 정보를 확인한다
[Actual result]
DXs의 DX 상태와 DX 상세 정보의 Stats의 상태 표기 오류
[Frequency]
Allway
[Severity/Priority]
Major

**Comment by sangb-han** [comment]
### 문제 분류
 * Defect (문제 아님)

### 해결 방법
 * 11/12 수정 배포됨

**Comment by TaeHoon-SNU** [comment]
혹시 수정된 버전이 어떻게 될까요?
0.1-21.11.5 버전에서 동일 증상이 발생하고 있습니다.
![image](https://user-images.githubusercontent.com/93699320/142134166-4f126b71-0aa3-4fc0-946d-32b77168309f.png)
![image](https://user-images.githubusercontent.com/93699320/142134447-582e52c8-59b2-46aa-9dab-11e2f2bceab0.png)
![image](https://user-images.githubusercontent.com/93699320/142134517-77112b72-6d05-4bff-b04a-e8e81361d0e4.png)
확인 부탁드립니다.
