### ISSUE TITLE
MX-Client(VIVEex) 추가 디스크 인식 불가 

### ISSUE THREAD

**Issue by mingeolyoo** [snuailab/autocare_issue_reporter#20]
[Pre-condition & Test Data]
MX-Client(VIVEex)

[Environment]
Mx-Client(VIVEex) Version: 4.2.0.32843, Ubuntu 20.04, autocare_docker S/W Version : 11/12배포 S/W

[Steps to reproduce]
리소스 트리 패널의 해당 서버 오른쪽 클릭 -> 서버 설정 -> 저장장치 관리자 탭 

[Expect result]
리소스 트리 패널의 해당 서버 오른쪽 클릭 -> 서버 설정 -> 저장장치 관리자 탭 -> 저장위치에 추가 디스크가 확인되어야 한다

[Actual result]
리소스 트리 패널의 해당 서버 오른쪽 클릭 -> 서버 설정 -> 저장장치 관리자 탭 -> 저장위치에 추가 디스크가 확인불가

[Frequency]
Allway

[Severity/Priority]
Critical

![서버설정](https://user-images.githubusercontent.com/93703111/142983618-51b65516-a102-44ca-b350-5ef8f6ee1164.JPG)

**Comment by jeongho2** [comment]
이슈 확인했고 task로 옮기겠습니다.

**Comment by sangb-han** [comment]
- Docker : Docker 내부에서만 
  - 기본 Storage 마운트가 필요하다. 
- Docker Without : 
@jeongho2 정책 확인 필요

**Comment by jeongho2** [comment]
김태훈 팀장님이 작성하신 문서입니다. 다음과 같이 Docker Compose에서 추가 디스크와 Docker 경로를 마운트하면 됩니다.

수동으로 추가 디스크 마운트 순서
disk check : fdisk -l
create partition : parted /dev/sdb → mklabel gpt → mkpart primary 0% 100% → p → q

disk check : fdisk -l
format : mkfs.ext4 /dev/sdb1

check UUID(/dev/sdb1) : blkid

edit fstab : nano /etc/fstab
add partition : UUID={new UUID} /mnt/mx_volume/storage ext4 defaults 0 0 )

UUID=7f467ae9-eedc-4eda-bd29-4a660c7bcec4 /mnt/mx_volume/storage ext4 defaults 0 0
mount : mkdir /mnt/mx_volume/storage → mount -a
mount check : df -h

change permission(upon initialization) : chmod -R 755 /mnt/mx_volume/storage

change docker-compose setting(add autocare_mx volumes) : nano docker-compose.yml

/mnt/mx_volume/storage:/storage:rw # storage
create folder inside docker(autocare_mx) : docker exec -it 81993b1c4ad0 /bin/bash

docker ps

mkdir /storage
chown viveex /storage
chgrp viveex /storage
