### ISSUE TITLE
AX에서 DX 모델 배포와 삭제 시 홀딩 증상 및 새로고침 오류 증상 발생

### ISSUE THREAD

**Issue by TaeHoon-SNU** [snuailab/autocare_issue_reporter#21]
[Pre-condition & Test Data]
웹페이지 실행 http://{IP address}:8000/frontend/console/

[Environment]
Ubuntu 20.04, autocare_docker S/W Version : 11/12 배포 S/W

[Steps to reproduce]
왼쪽 메뉴 리스트에서 Dxs 메뉴 클릭 → 배포할 DX Name의 DX 클릭 → Downloaded Apps 항목에서 배포할 모델 선택 → 모델 배포 버튼 클릭

[Expect result]
AX에서 DX 모델 배포와 삭제 시 정상적으로 작동되어야 한다 

[Actual result]
 → 모델 배포와 삭제를 여러 번 반복 실행 시 배포 홀딩 증상 발생
 → 모델 배포 후 새로고침 시 배포 작업이 다시 진행되며 Stats 아이콘에 나타났다 사라졌다 함
     (다른 화면 이동 후 재확인 시 증상 재현 안됨)
 → 모델 삭제 후 새로고침 시 삭제 작업이 다시 진행되며 배포 모델이 나타났다 사라졌다 함
     (다른 화면 이동 후 재확인 시 증상 재현 안됨)

[Frequency]
Allway

[Severity/Priority]
Critical

**Comment by jaypark-snuailab** [comment]
새로 고침 오류 : 0.1-21.11.24 배포 버전에서 수정됨
홀딩 증상 : 모델의 사이즈에 따라서 홀딩이 발생 할 수 있음. 0.1-21.11.24 다음 버전에서 수정 예정.
