### ISSUE TITLE
상세 정보 확인 화면에서 제어할 DX의 inference가 실행/중지/재실행 불가

### ISSUE THREAD

**Issue by TaeHoon-SNU** [snuailab/autocare_issue_reporter#22]
[Pre-condition & Test Data]
웹페이지 실행 http://{IP address}:8000/frontend/console/

[Environment]
Ubuntu 20.04, autocare_docker S/W Version : 11/12 배포 S/W

[Steps to reproduce]
왼쪽 메뉴 리스트에서 DXs 메뉴 클릭 → 상세 정보를 확인할 DX Name의 DX 클릭 → Stats의 DX의 실행/중지/재실행 버튼 클릭

[Expect result]
상세 정보 확인 화면에서 제어할 DX의 inference가 실행/중지/재실행되어야 한다

[Actual result]
상세 정보 확인 화면에서 제어할 DX의 inference가 실행/중지/재실행 불가

[Frequency]
Allway

[Severity/Priority]
Critical

**Comment by sangb-han** [comment]
Bug : 11/24 신규 UI 배포
