### ISSUE TITLE
DXs의 DX 상태와 DX 상세 정보의 Stats의 상태 표기 오류

### ISSUE THREAD

**Issue by TaeHoon-SNU** [snuailab/autocare_issue_reporter#23]
[Pre-condition & Test Data]
웹페이지 실행 http://{IP address}:8000/frontend/console/

[Environment]
Ubuntu 20.04, autocare_docker S/W Version : 11/12 배포 S/W

[Steps to reproduce]
왼쪽 메뉴 리스트에서 DXs 메뉴 클릭 → 상태 표기 확인
왼쪽 메뉴 리스트에서 DXs 메뉴 클릭 → 상세 정보를 확인할 DX Name의 DX 클릭 → 상태 표기 확인

[Expect result]
DXs의 DX 상태와 DX 상세 정보의 Stats의 상태 표기가 같아야 한다

[Actual result]
DXs의 DX 상태와 DX 상세 정보의 Stats의 상태 표기 다름

[Frequency]
Allway

[Severity/Priority]
Critical

**Comment by jaypark-snuailab** [comment]
BUG
11/24 배포 버전에서 수정.

**Comment by sangb-han** [comment]
신규 UI로 포트 등 변경
