### ISSUE TITLE
플러그인의 이벤트 알림과 즐겨찾기(북마크) 알림이 설정된 시간 간격으로 표출 불가

### ISSUE THREAD

**Issue by TaeHoon-SNU** [snuailab/autocare_issue_reporter#24]
[Pre-condition & Test Data]
MX-Client(VIVEex)

[Environment]
Mx-Client(VIVEex) Version: 4.2.0.32843, Ubuntu 20.04, autocare_docker S/W Version : 11/04 배포 S/W

[Steps to reproduce]
리소스 트리 패널의 카메라에서 마우스 오른쪽 버튼 클릭 후 카메라 설정 선택 → 카메라 설정 창에서 플러그인 탭 클릭 → 사용할 플러그인 활성화 후 적용 클릭 → Device Settings의 Notification Settings 항목의 Event Interver 시간 설정

[Expect result]
플러그인의 이벤트 알림과 즐겨찾기(북마크) 알림 표출 시간 변경 시 설정된 시간 간격으로 표출되어야 한다

[Actual result]
플러그인의 이벤트 알림과 즐겨찾기(북마크) 알림이 설정된 시간 간격으로 표출 불가

[Frequency]
Allway

[Severity/Priority]
Critical

**Comment by jeongho2** [comment]
해당 부분은 Deprecated된 설정으로, 차후 release에서 이벤트 발생 정의 후 재구현할 예정입니다.
