### ISSUE TITLE
AX Stream 페이지 오류 

### ISSUE THREAD

**Issue by mingeolyoo** [snuailab/autocare_issue_reporter#26]
**문제점 요약**
AX Stream 페이지에서 Media Source 목록 누락

**실행 환경**
- VIVEex Client : 4.2.0.32843
- 운영 체제 : Ubuntu 20.04
- SW Release : 11월 24일 배포

**재현 순서** 
문제점의 재현 순서를 다음과 같이 기술한다. 
1. MX 입력 영상 선택
2. MX 영상설정
3. MX 플러그인 탭
4. MX Vehicle 플러그인 활성화
5. 해당 Stream 객체 분석 활성화 

**예상 결과**
플러그인이 활성화된 Stream은 AX Stream 페이지 Media Source 목록에 표출 되어야 한다.

**실제 결과** 
처음 플러그인이 활성화된 Stream만 AX Stream 페이지 Media Source 목록에  표출된다.

**빈도**
Always

** 심각도**
Minor 

**추가 설명 / 스크린샷 / 동영상** 
![Media Source](https://user-images.githubusercontent.com/93703111/143964290-3a7838eb-1f3c-42fd-9ba0-55d2e7ef1fec.JPG)
[ax.log](https://github.com/snuailab/autocare_issue_reporter/files/7622010/ax.log)

**Comment by sangb-han** [comment]
종류 : 사양 변경 
원인 : DX에서 스트림을 자동 등록하면서, DX의 동작에 따라 표시/미표시 결정됨 
해결 : Inference를 자동 등록이 아닌 AX에서 Configuration 하는 것으로 변경됨 
적용 버전 : 2022/01/07
