### ISSUE TITLE
AX 페이지 새로고침 오류

### ISSUE THREAD

**Issue by mingeolyoo** [snuailab/autocare_issue_reporter#27]
**문제점 요약**

AX 페이지에서 새로고침 오류

**실행 환경**

- VIVEex Client ; 4.2.0.32843
- Edge , Chrome
- 운영 체제 : Ubuntu 20.04
- SW Release : 11월 24일 배포

**재현 순서** 

1. AX 시스템(페이지) 접속 
2. 새로고침

**예상 결과**

AX 페이지에서 새로고침시에 해당 페이지가 다시 보여야 한다.

**실제 결과** 

Not Found 표출 및 페이지 확인 불가

**빈도**

Always

** 심각도**

Critical 

**추가 설명 / 스크린샷 / 동영상** 
![f5](https://user-images.githubusercontent.com/93703111/143965190-7b581bca-5bd2-4533-9c67-10769596e3dc.JPG)
[ax.log](https://github.com/snuailab/autocare_issue_reporter/files/7622058/ax.log)

**Comment by sangb-han** [comment]
다음 릴리즈에서 해결


Linked Pull Request 
 * snuailab/autocare_ax#8 에서 해결
