### ISSUE TITLE
롱런테스트 MX Server 재시작 오류

### ISSUE THREAD

**Issue by mingeolyoo** [snuailab/autocare_issue_reporter#29]
**문제점 요약**
롱런테스트 MX Server 재시작 오류

**실행 환경**
- VIVEex Client : 4.2.032843
- 운영 체제 : Ubuntu 20.04
- SW Release : 11월 24일 배포

**재현 순서** 

1. AX 시스템 접속 
2. MX 입력 영상 선택
3. MX 영상설정
4. MX 플러그인 탭
5. Vehicle 플러그 활성화
6. MX 입력 영상 객체 검출 활성화

**예상 결과**

AX, DX, MX 초기 설정 상태를 유지 하며,  MX 입력 영상에서 객체 검출이 되어야 한다.

**실제 결과** 

MX Server가 재 시작 하여 해당 MX 입력 영상에서 객체 검출이 비활성화 된다.

**빈도**
Sometimes

** 심각도**

Critical 

**추가 설명 / 스크린샷 / 동영상** 

[로그.zip](https://github.com/snuailab/autocare_issue_reporter/files/7622617/default.zip)

https://user-images.githubusercontent.com/93703111/143978444-bcce794b-3fa9-4404-9b07-fbc06570d4c3.mp4

**Comment by mingeolyoo** [comment]
[log.zip](https://github.com/snuailab/autocare_issue_reporter/files/7658054/log.zip)

12 /06에 발생한 롱런테스트 서버 재시작 관련 새로운 로그 올려드립니다. 참고 부탁드립니다.  @jeongho2

**Comment by jeongho2** [comment]
해당 부분은 차후 Eternal release에 반영될 예정입니다.
