### ISSUE TITLE
Overview 정보 업데이트 불가

### ISSUE THREAD

**Issue by TaeHoon-SNU** [snuailab/autocare_issue_reporter#3]
[Pre-condition & Test Data]
웹페이지 실행 http://{IP address}:8000/frontend/console/
[Environment]
Ubuntu 20.04, autocare_docker S/W Version : 11/04 배포 S/W
[Steps to reproduce]
왼쪽 메뉴 리스트에서 Overview 메뉴 클릭 → 시스템 정보 입력 후 UPDATE 클릭
[Expect result]
시스템 정보가 업데이트되어야 한다
[Actual result]
시스템 정보 입력은 되나 업데이트 불가
[Frequency]
Allway
[Severity/Priority]
Minor

**Comment by jaypark-snuailab** [comment]
문제 분류

    Defect

해결 방법
   AX 문제로서 수정 완료되었습니다. 0.1-21.11.6-devel
