### ISSUE TITLE
AX({IP Address}/console/dx) DX Restart 버튼 동작 후 오류

### ISSUE THREAD

**Issue by mingeolyoo** [snuailab/autocare_issue_reporter#30]
**문제점 요약**
AX({IP Address}/console/dx}) DX Restart 버튼 동작 후 새로운 MX 입력 영상 플러그인 활성화 오류

**실행 환경**
- VIVEex Client : 4.2.0.32843
- 운영 체제 : Ubuntu 20.04
- SW Release : 11월 24일 배포

**재현 순서** 

1. AX 시스템 접속 
2. MX 입력 영상 선택
3. MX 영상설정
4. MX 플러그인 탭
5. Vehicle 플러그 enable
6. MX 입력 영상 객체 활성화
7. AX({IP Address}/console/dx}) DX Restart 버튼 클릭
8. 새로운 MX 입력 영상 플러그인 활성화 오류(Stream Assigned Failed)

**예상 결과**

DX Restart 버튼 동작시 현재 플러그인 활성화된 MX 입력 영상 객체 분석은 다시 수행되며, 새로운 MX 입력 영상 플러그인도 활성화 되어야 한다.

**실제 결과** 

DX Restart 버튼 동작시 현재 플러그인이 활성화된 MX 입력 영상은 객체 분석을 수행하지만, 새로운 MX 입력 영상 플러그인은 Stream Assigned Failed 알람이 발생된다.

**빈도**

Always

** 심각도**

Critical 

**추가 설명 / 스크린샷 / 동영상** 

[Restart logs.zip](https://github.com/snuailab/autocare_issue_reporter/files/7622855/Restart.logs.zip)

https://user-images.githubusercontent.com/93703111/143985034-a0f79fa5-7783-4af9-a0df-278ef62ee7c3.mp4

**Comment by jeongho2** [comment]
해당 문제는 eternals 릴리즈에서 해결될 예정입니다.
