### ISSUE TITLE
MX log 출력 오류

### ISSUE THREAD

**Issue by mingeolyoo** [snuailab/autocare_issue_reporter#31]
**문제점 요약**

MX log가 파일로 출력 되지 않는다.

**실행 환경**

- VIVEex Client : 4.2.0.32843
- 운영 체제 : Ubuntu 20.04
- SW Release : 11월 24일 배포

**재현 순서** 

1. CMD : /autocare_docker/mx/nx_ini/mediaserver_stderr.log(mediaserver_stdout.log)

**예상 결과**

(mediaserver_stderr.log , mediaserver_stdout.log)두 파일에 MX Log가 출력 되어야 한다.

**실제 결과** 
(mediaserver_stderr.log , mediaserver_stdout.log)두 파일에 MX Log가 출력 되지 않는다.

**빈도**

Always

** 심각도**

Critical 

**추가 설명 / 스크린샷 / 동영상** 

![mx 로그](https://user-images.githubusercontent.com/93703111/143987640-dace5e24-fff0-48d0-a74c-4848befdb9ed.JPG)

**Comment by jeongho2** [comment]
Mx에서 Service 실행 시 stdout 및 stderr를 log file로 redirect할 수 있는 기능을 지원합니다. 
해당 기능 동작하지 않고있어서 Mx 포럼에 관련 질문 남겨두었습니다.
https://support.networkoptix.com/hc/en-us/community/posts/4414471856919-OutputRedirector-does-not-work-

**Comment by jeongho2** [comment]
Nx 포럼 답변 확인결과, Nx에서 작성한 log redirect 사용법에 문제가 있었습니다.
해당 부분 답변대로 수정했고 동작확인했습니다. 다음 release에 반영하겠습니다.
