### ISSUE TITLE
네트워크 이슈(10 초간 데이터 받기 실패)

### ISSUE THREAD

**Issue by mingeolyoo** [snuailab/autocare_issue_reporter#32]
**문제점 요약**

네트워크 이슈(10 초간 데이터 받기 실패)

**실행 환경**

- VIVEex Client : 4.2.0.32843
- 운영 체제 : Ubuntu 20.04
- SW Release : 11월 24일 배포

**재현 순서** 

1. AX 시스템 접속 
2. MX 입력 영상 선택
3. MX 영상설정
4. MX 플러그인 탭
5. Vehicle 플러그인 활성화
6. MX 입력 영상 객체 설정 활성화
7. MX Client 에서 Ctrl + L (로그 확인)

**예상 결과**

네트워크 이슈 로그가 발생 하면 안된다.

**실제 결과** 

네트워크 이슈(10 초간 데이터 받기 실패) 로그 발생

**빈도**

Sometimes

** 심각도**

Defect 

**추가 설명 / 스크린샷 / 동영상** 

![Server 중단](https://user-images.githubusercontent.com/93703111/144172779-a61dc4fa-5a12-4f42-8499-f13e7485e317.JPG)
[ax.log](https://github.com/snuailab/autocare_issue_reporter/files/7630881/ax.log)
[VIVEex 서버 중단 MX log.txt](https://github.com/snuailab/autocare_issue_reporter/files/7630882/VIVEex.MX.log.txt)

**Comment by jeongho2** [comment]
해당 문제는 Streaming Server에서 스트리밍을 받아오지 못하는 경우입니다.
