### ISSUE TITLE
offline 설치 시 docker image 실행 오류 발생

### ISSUE THREAD

**Issue by TaeHoon-SNU** [snuailab/autocare_issue_reporter#33]
**문제점 요약**
offline 설치 시 docker image 실행 오류 발생

**실행 환경**
시스템이 실행된 환경을 말한다. 다음과 같은 정보를 입력한다. 
- 운영 체제 : Ubuntu 20.04
- SW Release : 11월 24일 배포

**재현 순서** 
문제점의 재현 순서를 다음과 같이 기술한다.
1. MX-Server(VIVEex)에서 터미널 실행
2. MX-Server(VIVEex) 터미널에서 Docker Image 압축 파일 생성
   → docker pull snuailab/autocare-ax:0.1-21.11.24-devel
   → docker save -o autocare-ax:0.1-21.11.5-devel.tar snuailab/autocare-ax:0.1-21.11.24-devel
3. docker image load
   → docker load -i autocare-ax:0.1-21.11.24-devel.tar
4. docker 실행
   → docker-compose up -d 
5. docker 실행 확인
   → docker-compose ps

**예상 결과**
offline 설치 시 docker image 가 정상적으로 실행되고 시스템이 동작해야 한다

**실제 결과** 
offline 설치 시 docker image 실행 오류 발생
Pulling 시 에러 메세지 발생
ERROR : The image for the service you're trying to recreate has been removed 메세지 발생

**빈도**
Always

** 심각도**
문제점의 심각도를 다음과 같이 기술한다. 
  - Critical : 중요한 기능이 동작하지 않거나, 다른 기능을 수행하는데 문제가 된다. 

**추가 설명 / 스크린샷 / 동영상** 
11월 12일 배포 버전에서 offline 설치 시 docker image 가 정상적으로 실행되고 시스템이 동작한다
![docker-compose 에러1](https://user-images.githubusercontent.com/93699320/144339422-8eb593a4-b615-446a-966c-d6535edeef00.png)

**Comment by snuailab-jinholee** [comment]
@jaypark-snuailab 님, @jeongho2 님. offline 설치시 발생하는 ERROR message 확인 부탁드립니다. 이미지에 보다 상세히 나오니 이미지를 확인하시는게 보다 정확해보입니다.
