### ISSUE TITLE
플러그인이 활성화된 MX 입력 영상에서 플러그인 비활성화시 객체 바운딩 박스 홀딩 에러

### ISSUE THREAD

**Issue by mingeolyoo** [snuailab/autocare_issue_reporter#34]
**문제점 요약**
MX 입력 영상 객체 바운딩 박스가 사라지지 않고 남아있는 문제

**실행 환경**
- VIVEex Client : 4.2.0.32843
- 운영 체제 : Ubuntu 20.04
- SW Release : 11월 24dlf 배포

**재현 순서** 

1. AX 시스템 접속 
2. MX 입력 영상 선택
3. MX 영상설정
4. MX 플러그인 탭
5. Vehicle 플러그 enable
6. 플러그인 활성화된 MX 입력 영상 객체 검출 활성화
7. 플러그인 활성화된 MX 입력 영상 객체 검출 비활성화

**예상 결과**

플러그인 활성화된 MX 입력 영상을 플러그인 비활성화하면  바운딩 박스가 사라져야 한다.

**실제 결과** 

플러그인 활성화된 MX 입력 영상을 플러그인 비활성화하면 바운딩 박스가 사라지지 않는다

**빈도**

Sometimes

** 심각도**

 Defect 

**추가 설명 / 스크린샷 / 동영상** 
[hw_log.log](https://github.com/snuailab/autocare_issue_reporter/files/7639983/hw_log.log)
[dx.log](https://github.com/snuailab/autocare_issue_reporter/files/7639984/dx.log)
[ax.log](https://github.com/snuailab/autocare_issue_reporter/files/7639985/ax.log)
[log_file.log](https://github.com/snuailab/autocare_issue_reporter/files/7639986/log_file.log)
![스크린샷, 2021-12-02 13-24-49](https://user-images.githubusercontent.com/93703111/144379617-2d5a7a90-cc20-4e1f-bd9c-334e5136b047.png)
![스크린샷, 2021-12-02 13-24-50](https://user-images.githubusercontent.com/93703111/144379622-d73007f8-8c95-445c-9ff3-ec24bb9e3e30.png)

**Comment by jeongho2** [comment]
해당 문제는 Mx Client 자체 버그입니다. 현재는 해당 영상을 내렸다고 올리면 객체 바운딩 박스가 사라집니다.
