### ISSUE TITLE
멀티(외부)DX Discover 이후 추가 스트림(Stream Assigned Failed)

### ISSUE THREAD

**Issue by mingeolyoo** [snuailab/autocare_issue_reporter#35]
**문제점 요약**

멀티(외부)DX Discover 이후 추가 스트림(Stream Assigned Failed)

**실행 환경**
- VIVEex Client : 4.2.0.32843
- 운영 체제 : Ubuntu  18.04 
- SW Release : 11월 24일 배포

**재현 순서** 

B 장비(192.168.0.57):DX 설치

A 장비(192.168.0.58) : AX, DX, MX 설치
1. AX(192.168.0.58:8000)  시스템 접속 
2. MX 입력 영상 선택
3. MX 영상설정
4. MX 플러그인 탭
5. Vehicle 플러그인 활성화
6. MX 입력 영상 객체 활성화
7. AX(192.168.0.58:8000) 시스템 접속 및 추가 DX Discover(192.168.0.57)
8. 새로운 MX 입력 영상 선택
9. MX 영상설정
10. MX 플러그인 탭
11. Vehicle 플러그인 활성화
12. Stream Assigned Failed 오류 발생

**예상 결과**

MX 입력 영상 플러그인 활성화시 Stream Assigned succeess 가 발생해야 된다.

**실제 결과** 

MX 입력 영상 플러그인 활성화시 Stream Assigned Failed가 발생된다.

**빈도**

Always

** 심각도**
 
Defect 

**추가 설명 / 스크린샷 / 동영상** 
[logs.zip](https://github.com/snuailab/autocare_issue_reporter/files/7658026/logs.zip)

https://user-images.githubusercontent.com/93703111/144789265-c01d6165-7d6a-436a-85d7-65d5466deef9.mp4

**Comment by jaypark-snuailab** [comment]
이전 버전에서 발생할 수 있는 문제로 새 버전에서는 발행하지 않을 것으로 보입니다.
