### ISSUE TITLE
DX에 저장되는 로그의 날짜 형식이 다름

### ISSUE THREAD

**Issue by TaeHoon-SNU** [snuailab/autocare_issue_reporter#37]
**문제점 요약**
DX에 저장되는 로그의 날짜 형식이 다름

**실행 환경**
시스템이 실행된 환경을 말한다. 다음과 같은 정보를 입력한다. 
- 운영 체제 : Ubuntu 20.04
- SW Release : 11월 24일 배포

**재현 순서** 
문제점의 재현 순서를 다음과 같이 기술한다. 
1. MX-Server(VIVEex)에서 터미널 실행
2. MX 로그 확인 : docker exec -it autocare_docker_autocare_mx_1 /bin/bash → cd /config/var/log → cat hw_log.log → cat log_file.log
3. AX 로그 확인 : docker exec -it autocare_docker_autocare_ax_1 /bin/bash → cd /opt/autocare/autocare_ax → cat ax.log
4. DX 로그 확인 : docker exec -it autocare_docker_autocare_dx_1 /bin/bash → cd /opt/autocare/dx/resources/tmp/logs → cat dx.log

**예상 결과**
AutoCare System의 저장되는 모든 시스템 로그의 날짜 형식을 동일하게 저장되어야 한다

**실제 결과** 
DX에 저장되는 로그의 날짜 형식이 다름
 - AX : yyyy-mm-dd hh:mm:ss(24H 기준)
 - MX : yyyy-mm-dd hh:mm:ss(24H 기준)
 - DX : hh:mm:ss (12H 기준)
   → DX 로그 저장 시간 너무 짧음(약15분)

**빈도**
Always

** 심각도**
Minor

**추가 설명 / 스크린샷 / 동영상** 
![DX 로그 표출](https://user-images.githubusercontent.com/93699320/145534440-8dcdb0de-3fd6-421c-9c5c-5feb64dfd64b.png)

**Comment by jaeminjeon-snuailab** [comment]
다음 release에서 logger 수정 반영될 예정입니다.
