### ISSUE TITLE
dx 제거 후 재등록 불가

### ISSUE THREAD

**Issue by TaeHoon-SNU** [snuailab/autocare_issue_reporter#38]
**문제점 요약**
dx 제거 후 재등록 불가

**실행 환경**
- 운영 체제 : Ubuntu 20.04
- SW Release : 11월 24일 배포

**재현 순서** 
1. MX-Client(VIVEex) 프로그램 실행
2. 리소스 트리 패널의 서버에서 추가된 카메라를 마우스 드래그 앤 드롭으로 보기 그리드 화면으로 이동
3. 리소스 트리 패널의 카메라에서 마우스 오른쪽 버튼 클릭 후 카메라 설정 선택
4. 카메라 설정 창에서 플러그인 탭 클릭
5. 활성화할 플러그인 선택
6. 활성화 버튼 클릭
7. 카메라 영상에서 마우스 오른쪽 버튼 클릭 후 아이템표시의 객체 선택
8. 스트리밍서버 문제로 영상 연결 불가
9. 스트리밍서버 영상 재연결(객체 검출 중지됨)
10. http://{IP address}:8000 웹페이지 접속
11. 왼쪽 메뉴 리스트에서 DX 메뉴 클릭
12. Status 항목에서 Disable 클릭
13. Status 항목에서 Enable 클릭(복구 불가)
14. Status 항목에서 Restart 클릭(복구 불가)
15. Status 항목에서 Remove 클릭
16. 오른쪽 상단 Discover 클릭

**예상 결과**
dx 제거 후 재등록되어야 한다

**실제 결과** 
dx 제거 후 재등록 불가
 - 영상 스트림 연결 불가 후 재연결하고 DX를 Disable/Enable, Restart 시켰을 시 복구 불가
 - 복구가 안되어 DX를 Remove 후 재등록 불가

**빈도**
Once(현재 1번 확인됨)

** 심각도**
Critical

**추가 설명 / 스크린샷 / 동영상** 
1. 약 1일 후에도 자동 복구 불가
2. docker-compose restart 로 복구

[dx 제거 후 재등록 불가_log.zip](https://github.com/snuailab/autocare_issue_reporter/files/7709805/dx._log.zip)

![K-056](https://user-images.githubusercontent.com/93699320/145951970-edf43ddf-c299-4e2f-8d62-735f1bd10b12.png)

**Comment by snuailab-jinholee** [comment]
ax 에서 dx remove 이후에 discover 시 ax 는 로그가 있지만, dx 에는 nats.io 쪽 로그가 안보임.
ax 검토가 필요한 이슈.
추후 release 에 개선 여부 확인 필요.

**Comment by jaypark-snuailab** [comment]
이전버전 문제로 새 버전에서는 발생하지 않은 문제입니다. 재연해보시고 발생하면 다시 등록바랍니다.
