### ISSUE TITLE
DX 중지 후 실행/재실행 시 Stream 정보 확인 불가

### ISSUE THREAD

**Issue by TaeHoon-SNU** [snuailab/autocare_issue_reporter#4]
[Pre-condition & Test Data]
웹페이지 실행 http://{IP address}:8000/frontend/console/
[Environment]
Ubuntu 20.04, autocare_docker S/W Version : 11/04 배포 S/W
[Steps to reproduce]
왼쪽 메뉴 리스트에서 Dxs 메뉴 클릭 → 상세 정보를 확인할 DX Name의 DX 클릭 → Stats의 DX의 중지 버튼 클릭 → Stats의 DX의 재실행 버튼 클릭
[Expect result]
제어할 DX의 inference가 수행 중 재실행되어야 한다
[Actual result]
DX 중지 후 실행/재실행 시 Stream 정보 확인 불가
[Frequency]
Allway
[Severity/Priority]
Critical

**Comment by jaypark-snuailab** [comment]
문제가 아님.

DX 중지 버튼을 클릭하면 수행중이던 모든 Inference가 중지되며 이후 해당 DX는 Inference를 수행하지 않는 상태가 입니다.
이후 다시 시작버튼을 누르면 Inference 가능 상태가 딥니다. (이전 수행중이던 Inference가 다시 시작되는 것이 아님)
따라서 Inference를 다시 시작 하려면 MX에서 Plugin을 off 한 후 다시 on해야 합니다.
