### ISSUE TITLE
각 페이지에서 새로고침 작업 시 페이지 이름이 dashboard로 변경

### ISSUE THREAD

**Issue by TaeHoon-SNU** [snuailab/autocare_issue_reporter#41]
**문제점 요약**
각 페이지에서 새로고침 작업 시 페이지 이름이 dashboard로 변경

**실행 환경**
- 운영 체제 : Ubuntu 20.04
- SW Release : 22년01월06일 배포

**재현 순서** 
1. http://{IP address}:8000 웹페이지 접속
2. 왼쪽 메뉴 리스트에서 DX 메뉴 클릭
3. 새로고침(F5키 입력 or 새로고침 버튼 클릭)
4. 왼쪽 메뉴 리스트에서 Model 메뉴 클릭
5. 새로고침(F5키 입력 or 새로고침 버튼 클릭)
6. 왼쪽 메뉴 리스트에서 Stream메뉴 클릭
7. 새로고침(F5키 입력 or 새로고침 버튼 클릭)
8. 왼쪽 메뉴 리스트에서 Settings/System 메뉴 클릭
9. 새로고침(F5키 입력 or 새로고침 버튼 클릭)
10. 왼쪽 메뉴 리스트에서 Settings/User 메뉴 클릭
11. 새로고침(F5키 입력 or 새로고침 버튼 클릭)

**예상 결과**
각 페이지별 새로고침 작업 시 해당 페이지의 이름이 확인되어야 한다

**실제 결과** 
각 페이지에서 새로고침 작업 시 페이지 이름 변경

**빈도**
Always

** 심각도**
Minor

**추가 설명 / 스크린샷 / 동영상** 
![Stream 페이지에 새로고침 진행 시 상단에 이름이 dashboard로 변경1](https://user-images.githubusercontent.com/93699320/149128945-4dc8814d-af67-4bb0-933b-c962ff631fc9.png)
![Stream 페이지에 새로고침 진행 시 상단에 이름이 dashboard로 변경2](https://user-images.githubusercontent.com/93699320/149128963-159364c6-c983-4795-9675-0255ab8af9eb.png)

**Comment by sangb-han** [comment]
분류 : 수정
원인 : Click 시에 Title을 변경하도록 함. Reload는 Click에 해당하지 않음
해결 
  - Reload시에 Title을 변경하도록 변경 

버전 : 2022/1/21
