### ISSUE TITLE
DX 이름 중복으로 Stream의 Add chain 작업 중 DX 선택 시 혼선 발생

### ISSUE THREAD

**Issue by TaeHoon-SNU** [snuailab/autocare_issue_reporter#42]
**문제점 요약**
DX 이름 중복으로 Stream의 Add chain 작업 중 DX 선택 시 혼선 발생

**실행 환경**
- 운영 체제 : Ubuntu 20.04
- SW Release : 22년01월06일 배포

**재현 순서** 
"1. http://{IP address}:8000 웹페이지 접속
2. 왼쪽 메뉴 리스트에서 DX 메뉴 클릭
3. 오른쪽 상단 Discover 클릭
4. 추가할 DX에서 ADD DX 버튼 클릭
5. CLOSE 버튼 클릭
6. 오른쪽 상단 Discover 클릭
7. 추가할 DX에서 ADD DX 버튼 클릭
8. CLOSE 버튼 클릭"

**예상 결과**
멀티 DX 추가 시 DX별로 이름이 설정되어야 한다

**실제 결과** 
DX 이름 중복으로 Stream의 Add chain 작업 중 DX 선택 시 혼선 발생
운영 중에 DX 추가 삭제 시 순서가 변경될 수 있음

**빈도**
Always

** 심각도**
Major

**추가 설명 / 스크린샷 / 동영상** 
![DX 명칭 중복으로 인한 작업 혼선1](https://user-images.githubusercontent.com/93699320/149129649-c1a9fc48-fcd2-405e-a14a-bfcc2cd00ad5.png)
![DX 명칭 중복으로 인한 작업 혼선2](https://user-images.githubusercontent.com/93699320/149129657-f2adb173-350c-4746-a6b1-d2ebb8e379cb.png)
![DX 명칭 중복으로 인한 작업 혼선3](https://user-images.githubusercontent.com/93699320/149129668-0134a192-c74c-46ff-a8c5-5f1dfc1019b1.png)

**Comment by jaypark-snuailab** [comment]
다음과 같이 DX 선택시 표시에 IP 추가하여 혼선 없앰
DX_이름 / IP
1/21 릴리즈에 반영예정
@sangb-han
