### ISSUE TITLE
멀티 MX 추가 시 스트림 명칭이 중복되면 첫번째에 등록된 스트림 명칭 표시 불가

### ISSUE THREAD

**Issue by TaeHoon-SNU** [snuailab/autocare_issue_reporter#43]
**문제점 요약**
멀티 MX 추가 시 스트림 명칭이 중복되면 첫번째에 등록된 스트림 명칭 표시 불가

**실행 환경**
- 운영 체제 : Ubuntu 20.04
- SW Release : 22년01월06일 배포

**재현 순서** 
1. http://{IP address}:8000 웹페이지 접속
2. 왼쪽 메뉴 리스트에서 Stream 메뉴 클릭
3. 오른쪽 상단 ADD MX 클릭
4. 추가할 MX의 IP 입력
5. 추가할 MX의 Port 입력
6. MANUAL ADD 클릭
7. 추가할 MX의 ID 입력
8. 추가할 MX의 Password 입력
9. ADD 버튼 클릭
10. CLOSE 버튼 클릭
11. 추가할 MX의 IP 입력
12. 추가할 MX의 Port 입력
13. MANUAL ADD 클릭
14. 추가할 MX의 ID 입력
15. 추가할 MX의 Password 입력
16. ADD 버튼 클릭
17. CLOSE 버튼 클릭

**예상 결과**
멀티 MX 추가 시 MX별로 스트림이 확인되어야 한다

**실제 결과** 
멀티 MX 추가 시 스트림 명칭이 중복되면 첫번째에 등록된 스트림 명칭 표시 불가

**빈도**
Always

** 심각도**
Critical

**추가 설명 / 스크린샷 / 동영상** 
![멀티 MX 추가 시 스트림 명칭이 중복되면 첫번째에 등록된 스트림 명칭 표시 불가1](https://user-images.githubusercontent.com/93699320/149132246-9c3e5c66-1038-4898-b768-480fb3fe13dd.png)
![멀티 MX 추가 시 스트림 명칭이 중복되면 첫번째에 등록된 스트림 명칭 표시 불가2](https://user-images.githubusercontent.com/93699320/149132255-6ce6455d-59bb-41a9-8fee-79f347bd0d3b.png)

**Comment by sangb-han** [comment]
원인 : Stream ID가 고유하지 않음
분류 : 코드 수정
결과 : Stream ID를 MX ID와 조합하여 ID로 생성 
적용 버전 : 2022/1/21
