### ISSUE TITLE
MX의 스트림 명칭 중복 시 DX와 Stream 페이지의 스트림 정보 불일치

### ISSUE THREAD

**Issue by TaeHoon-SNU** [snuailab/autocare_issue_reporter#44]
**문제점 요약**
MX의 스트림 명칭 중복 시 DX와 Stream 페이지의 스트림 정보 불일치

**실행 환경**
- 운영 체제 : Ubuntu 20.04
- SW Release : 22년01월06일 배포

**재현 순서** 
1. http://{IP address}:8000 웹페이지 접속
2. 왼쪽 메뉴 리스트에서 Stream 메뉴 클릭
3. 오른쪽 상단 ADD MX 클릭
4. 추가할 MX의 IP 입력
5. 추가할 MX의 Port 입력
6. MANUAL ADD 클릭
7. 추가할 MX의 ID 입력
8. 추가할 MX의 Password 입력
9. ADD 버튼 클릭
10. CLOSE 버튼 클릭
11. 설정할 MX의 왼쪽 + 버튼 클릭
12. 설정할 스트림의 오른쪽 Add chain 버튼 클릭
13. Vision App 항목에서 적용할 플러그인 선택
14. Analytics 항목에서 적용할 모델 선택
15. DX 항목에서 적용할 DX 선택
16. CONFIRM 버튼 클릭

**예상 결과**
MX에서 객체 검출 설정 시 MX별로 스트림이 정확하게 표출되어야 한다

**실제 결과** 
MX의 스트림 명칭 중복 시 DX와 Stream 페이지의 스트림 정보 불일치

**빈도**
Always

** 심각도**
Critical

**추가 설명 / 스크린샷 / 동영상** 
![MX의 스트림 명칭 중복 시 DX와 Stream 정보 불일치1](https://user-images.githubusercontent.com/93699320/149133508-f0d67715-64a2-4623-a3fb-86757b9e99f1.png)
![MX의 스트림 명칭 중복 시 DX와 Stream 정보 불일치2](https://user-images.githubusercontent.com/93699320/149133516-59d2cb1f-8a29-4b95-a6ab-72b3e4940fa2.png)

**Comment by sangb-han** [comment]
원인 : StreamId 처리 미흡 
해결 : Stream ID 추가
