### ISSUE TITLE
Add chain 작업 시 Vision App의 항목 정리 필요

### ISSUE THREAD

**Issue by TaeHoon-SNU** [snuailab/autocare_issue_reporter#47]
**문제점 요약**
Add chain 작업 시 Vision App의 항목 정리 필요

**실행 환경**
- 운영 체제 : Ubuntu 20.04
- SW Release : 22년01월06일 배포

**재현 순서** 
1. http://{IP address}:8000 웹페이지 접속
2. 왼쪽 메뉴 리스트에서 Stream 메뉴 클릭
3. 오른쪽 상단 ADD MX 클릭
4. 추가할 MX의 IP 입력
5. 추가할 MX의 Port 입력
6. MANUAL ADD 클릭
7. 추가할 MX의 ID 입력
8. 추가할 MX의 Password 입력
9. ADD 버튼 클릭
10. CLOSE 버튼 클릭
11. 설정할 MX의 왼쪽 + 버튼 클릭
12. 설정할 스트림의 오른쪽 Add chain 버튼 클릭
13. Vision App 항목에서 적용할 플러그인 선택

**예상 결과**
MX에서 객체 검출 설정 시 Vision App 항목에 AutoCare 플러그인만 설정되어야 한다

**실제 결과** 
Add chain 작업 시 Vision App의 항목 정리 필요
VIVEex 기본 플러그인 제외 필요

**빈도**
Always

** 심각도**
Minor

**추가 설명 / 스크린샷 / 동영상** 
![Add chain 작업 시 select app의 항목 정리 필요(VIVEex 기본 플러그인 제외 필요)](https://user-images.githubusercontent.com/93699320/149136227-2294f4e3-e573-40af-9079-1366569914b1.png)

**Comment by jaypark-snuailab** [comment]
1.10일 릴리즈에서 수정됨.
