### ISSUE TITLE
DX 페이지에서 새로고침 작업 시 DX 정보 표기 오류

### ISSUE THREAD

**Issue by TaeHoon-SNU** [snuailab/autocare_issue_reporter#48]
**문제점 요약**
DX 페이지에서 새로고침 작업 시 DX 정보 표기 오류

**실행 환경**
- 운영 체제 : Ubuntu 20.04
- SW Release : 22년01월06일 배포

**재현 순서** 
1. http://{IP address}:8000 웹페이지 접속
2. 왼쪽 메뉴 리스트에서 DX 메뉴 클릭
3. 오른쪽 상단 Discover 클릭
4. 추가할 DX에서 ADD DX 버튼 클릭
5. CLOSE 버튼 클릭
6. 새로고침(F5키 입력 or 새로고침 버튼 클릭)
7. 오른쪽 상단 Discover 클릭
8. 추가할 DX에서 ADD DX 버튼 클릭
9. CLOSE 버튼 클릭
10. 새로고침(F5키 입력 or 새로고침 버튼 클릭)

**예상 결과**
DX 페이지에서 새로고침 작업 시 DX 정보가  표출되어햐 한다

**실제 결과** 
DX 페이지에서 새로고침 작업 시 DX 정보 표기 오류

**빈도**
Always

** 심각도**
Minor

**추가 설명 / 스크린샷 / 동영상** 
![DX 페이지에서 새로고침 작업 시 DX 정보 표기 오류1](https://user-images.githubusercontent.com/93699320/149136903-6105c9a6-dd7b-4736-acea-83ff15ba0b1c.png)
![DX 페이지에서 새로고침 작업 시 DX 정보 표기 오류2](https://user-images.githubusercontent.com/93699320/149136911-a352e062-4f84-4fd9-8333-0904f11c2896.png)
![DX 페이지에서 새로고침 작업 시 DX 정보 표기 오류3](https://user-images.githubusercontent.com/93699320/149136912-7bde53b6-157f-4012-9915-d84fc2176c2c.png)
![DX 페이지에서 새로고침 작업 시 DX 정보 표기 오류4](https://user-images.githubusercontent.com/93699320/149136916-e2a63349-84b7-45dc-a316-6db470db90f7.png)
![DX 페이지에서 새로고침 작업 시 DX 정보 표기 오류5](https://user-images.githubusercontent.com/93699320/149136921-aa0b9efd-0370-45d2-bbc1-9c6233502109.png)

**Comment by snuailab-jinholee** [comment]
@jaypark-snuailab 님. 어제 구두로 개선되었다고 말씀하신 이슈로 보입니다. 개선 관련 정보 입력 후 이슈 처리 부탁드립니다.

**Comment by jaypark-snuailab** [comment]
@sangb-han 확인 바랍니다.

**Comment by sangb-han** [comment]
원인 : 파싱 처리에 문제가 있음(model이 null이 되는 문제) 
해결 : model 에 null 처리 추가
