### ISSUE TITLE
AX에서 DX 모델 배포/삭제 오류

### ISSUE THREAD

**Issue by TaeHoon-SNU** [snuailab/autocare_issue_reporter#5]
[Pre-condition & Test Data]
웹페이지 실행 http://{IP address}:8000/frontend/console/

[Environment]
Ubuntu 20.04, autocare_docker S/W Version : 11/04 배포 S/W

[Steps to reproduce]
왼쪽 메뉴 리스트에서 Dxs 메뉴 클릭 → 배포할 DX Name의 DX 클릭 → Downloaded Apps 항목에서 배포할 모델 선택 → 모델 배포 버튼 클릭

[Expect result]
DX에 배포할 모델을 선택하여 배포 시 모델이 배포/삭제되어야 한다

[Actual result]
모델 선택 후 배포/삭제 버튼 클릭 시 Internal Server Error 발생 및 모델 배포/삭제 완료에 대한 경고 메시지 미발생

[Frequency]
Allway

[Severity/Priority]
Critical

**Comment by sangb-han** [comment]
신규 UI에서 수정 예정으로 현재 UI에서는 수정하지 않음 

11/24 신규 배포
