### ISSUE TITLE
DX 로그 내부의 timestap의 날짜 형식이 다름

### ISSUE THREAD

**Issue by TaeHoon-SNU** [snuailab/autocare_issue_reporter#50]
**문제점 요약**
DX 로그 내부의 timestap의 날짜 형식이 다름

**실행 환경**
- 운영 체제 : Ubuntu 20.04
- SW Release : 22년01월06일 배포

**재현 순서** 
1. MX-Server(VIVEex)에서 터미널 실행
2. DX 로그 확인 : docker exec -it autocare_docker_autocare_dx_1 /bin/bash → cd /opt/autocare/dx/resources/tmp/logs → cat dx.log

**예상 결과**
DX System의 저장되는 시스템 로그의 날짜 형식을 동일하게 저장되어야 한다

**실제 결과** 
DX 로그 내부의 timestap의 날짜 형식이 다름
DX 로그 날짜 형식 : yyyy-mm-dd hh:mm:ss
DX 로그 내부의 timestap의 날짜 형식 : yyyy-01-mm/dd/22 hh:mm:ss

**빈도**
Always

** 심각도**
Minor

**추가 설명 / 스크린샷 / 동영상** 
![DX 타임스탬프 표기 형식 오류](https://user-images.githubusercontent.com/93699320/149138890-a82af1f3-57a4-488d-9930-69fb1c228384.png)

**Comment by jaeminjeon-snuailab** [comment]
DX inspect 의 날짜 형식 변경하여 추후 배포 버전에 반영 예정입니다.
- https://github.com/snuailab/autocare_dx/pull/44
