### ISSUE TITLE
DX 상세 정보 페이지에서 새로고침 작업 후 Stream에 Add chain 작업 시 데이터 확인 불가

### ISSUE THREAD

**Issue by TaeHoon-SNU** [snuailab/autocare_issue_reporter#51]
**문제점 요약**
DX 상세 정보 페이지에서 새로고침 작업 후 Stream에 Add chain 작업 시 데이터 확인 불가

**실행 환경**
- 운영 체제 : Ubuntu 20.04
- SW Release : 22년01월06일 배포

**재현 순서** 
1. http://{IP address}:8000 웹페이지 접속
2. 왼쪽 메뉴 리스트에서 DX 메뉴 클릭
3. 상세 정보를 확인할 DX Name의 DX 클릭
4. Models의 Downloaded Models 항목에서 + 버튼 클릭 
5. 다운로드할 모델 선택
6. 설정할 MX의 왼쪽 + 버튼 클릭
7. 설정할 스트림의 오른쪽 Add chain 버튼 클릭
8. Vision App 항목에서 적용할 플러그인 선택
9. Analytics 항목에서 적용할 모델 선택
10. DX 항목에서 적용할 DX 선택
11. CONFIRM 버튼 클릭
12. 상세 정보를 확인할 DX Name의 DX 클릭
13. Models의 Downloaded Models 항목에서 + 버튼 클릭 
14. 새로고침(F5키 입력 or 새로고침 버튼 클릭)

**예상 결과**
DX 상세 정보 페이지에서 새로고침 작업 시 DX 상세 정보를 표출할 수 있다

**실제 결과** 
DX 상세 정보 페이지에서 새로고침 작업 후 Stream에 Add chain 작업 시 데이터 확인 불가
DX 상세 정보 페이지에서 새로고침 작업 시 Models과 Media Source가 확인 불가
Stream에 Add chain 작업 시 Select analytic의 데이터 확인 불가

**빈도**
Always

** 심각도**
Critical

**추가 설명 / 스크린샷 / 동영상** 
![DX 상세 정보 페이지에서 새로고침 작업 시 Models과 Media Source가 확인 불가(Stream에 Add chain 작업 시 Select analytic의 데이터 확인 불가)1 ](https://user-images.githubusercontent.com/93699320/149139783-8f621ddc-ca5b-461f-9ba9-19dd5a91e2bd.png)
![DX 상세 정보 페이지에서 새로고침 작업 시 Models과 Media Source가 확인 불가(Stream에 Add chain 작업 시 Select analytic의 데이터 확인 불가)2](https://user-images.githubusercontent.com/93699320/149139786-32d555bd-5726-467b-8329-eb3a088d224a.png)
![DX 상세 정보 페이지에서 새로고침 작업 시 Models과 Media Source가 확인 불가(Stream에 Add chain 작업 시 Select analytic의 데이터 확인 불가)3](https://user-images.githubusercontent.com/93699320/149139788-f163822c-2887-4717-b45a-8311b6596deb.png)

**Comment by jaypark-snuailab** [comment]
@sangb-han 새로 고침시 상세 정보 표시가 안된다는 문제 입니다. 확인 바랍니다.

**Comment by sangb-han** [comment]
원인 : DX 상세 페이지에서는 전체 정보를 업로딩하지 않음
종류 : 코드 수정 
해결 방법 
  - DX 상세 페이지는 삭제 예정 
  - MX 페이지는 항상 모든 정보를 로딩 

적용 버전: 2022/1/21

Refs : snuailab/autocare_ax_webapp#85
