### ISSUE TITLE
DX 추가 후 Discover 클릭 시 등록된 DX도 확인

### ISSUE THREAD

**Issue by TaeHoon-SNU** [snuailab/autocare_issue_reporter#52]
**문제점 요약**
DX 추가 후 Discover 클릭 시 등록된 DX도 확인

**실행 환경**
- 운영 체제 : Ubuntu 20.04
- SW Release : 22년01월06일 배포

**재현 순서** 
1. http://{IP address}:8000 웹페이지 접속
2. 왼쪽 메뉴 리스트에서 DX 메뉴 클릭
3. 오른쪽 상단 Discover 클릭
4. 추가할 DX에서 ADD DX 버튼 클릭
5. CLOSE 버튼 클릭
6. 오른쪽 상단 Discover 클릭
7. 추가할 DX에서 ADD DX 버튼 클릭
8. CLOSE 버튼 클릭
9. 오른쪽 상단 Discover 클릭

**예상 결과**
DX 추가 후 Discover 클릭 시 등록된 DX는 제외되어야 한다

**실제 결과** 
DX 추가 후 Discover 클릭 시 등록된 DX도 확인

**빈도**
Always

** 심각도**
Minor

**추가 설명 / 스크린샷 / 동영상** 
![DX 추가 후 Discover 클릭 시 등록된 DX도 확인](https://user-images.githubusercontent.com/93699320/149140465-28fd5c98-0142-43d0-a9b6-8efbc0daf00d.png)

**Comment by jaypark-snuailab** [comment]
Discover시 등록된 DX 포함 모든 DX가 표시되는 것이 현재 사양입니다. 이미 등록된 DXᅟ를 다시 등록할 경우 ID가 같다면 새로운 정보로 업데이트 됩니다.
