### ISSUE TITLE
DX페이지 이동 시 Download Model이 1개인데 여러 개로 표출

### ISSUE THREAD

**Issue by TaeHoon-SNU** [snuailab/autocare_issue_reporter#53]
**문제점 요약**
DX페이지 이동 시 Download Model이 1개인데 여러 개로 표출

**실행 환경**
- 운영 체제 : Ubuntu 20.04
- SW Release : 22년01월06일 배포

**재현 순서** 
1. http://{IP address}:8000 웹페이지 접속
2. 왼쪽 메뉴 리스트에서 DX 메뉴 클릭
3. 오른쪽 상단 Discover 클릭
4. 추가할 DX에서 ADD DX 버튼 클릭
5. CLOSE 버튼 클릭
6. 오른쪽 상단 Discover 클릭
7. 추가할 DX에서 ADD DX 버튼 클릭
8. CLOSE 버튼 클릭
9. 왼쪽 메뉴 리스트에서 다른 메뉴 클릭
10. 왼쪽 메뉴 리스트에서 DX 메뉴 클릭

**예상 결과**
DX 추가 후 다른 페이지 이동 후 DX 페이지 이동 시 DX 정보를 정확하게 표출할 수 있다

**실제 결과** 
DX페이지 이동 시 Download Model이 1개인데 여러 개로 표출

**빈도**
Sometimes

** 심각도**
Minor

**추가 설명 / 스크린샷 / 동영상** 
![DX페이지 이동 시 Download Model이 1개인데 여러 개로 표출1](https://user-images.githubusercontent.com/93699320/149141193-c8b4523f-2f71-41f8-af46-8fa413b672ce.png)
![DX페이지 이동 시 Download Model이 1개인데 여러 개로 표출2](https://user-images.githubusercontent.com/93699320/149141196-17fd6c6e-7ce2-4966-8987-f4dda6d3e7c0.png)

**Comment by snuailab-jinholee** [comment]
@jaypark-snuailab 님. DX 웹페이지 정보 오류 문제입니다. 검토 부탁드립니다.
+ CC. @jaypark-snuailab 님.

**Comment by jaypark-snuailab** [comment]
@TaeHoon-SNU 상세한 재연 방법 부탁드립니다. download 모델이 1개인데 여러개 표출이라고 하셨는데 1개 인 것은 어떻게 확인하셨는지요? 테스트 중에 DX에 model이 여러개 올라가 있다가 AX만 재시작한 경우 DX를 등록 하면 기존에 download 된 Model이 표시되는 것은 정상입니다. 확인 부탁드립니다.

**Comment by jaypark-snuailab** [comment]
@sangb-han 스크린 캡처를 보면 download model 정보가 바르게 표시되다가 다시고침을 하면 두개의 DX가 같은 정보를 표시하는 것 같습니다. 확인 바랍니다.

**Comment by TaeHoon-SNU** [comment]
![DX페이지 이동 시 Download Model이 1개인데 여러 개로 표출3](https://user-images.githubusercontent.com/93699320/149686225-c59910ee-84e3-47d2-965b-19b8fc347a5d.png)
지금 첨부한 스크린 캡처는 등록된 Model이 1개이고 + 버튼 클릭 시 추가로 등록할 Model(Default 제외)이 없는 상황에 대한 내용입니다.
해당 증상이 새로고침 시 발생하는 증상은 아니고 다른 페이지에서 DX 페이지로 이동 시 간헐적으로 발생하는 증상입니다.

**Comment by jaypark-snuailab** [comment]
데이터 로딩 문제로 수정했습니다.
