### ISSUE TITLE
기본 설정(Model 추가 + DX 추가 및 Model 다운로드 + MX 추가) 후 항상 MX가 객체 검출 설정 오류

### ISSUE THREAD

**Issue by TaeHoon-SNU** [snuailab/autocare_issue_reporter#54]
**문제점 요약**
기본 설정(Model 추가 + DX 추가 및 Model 다운로드 + MX 추가) 후 항상 MX가 객체 검출 설정 오류

**실행 환경**
운영 체제 : Ubuntu 20.04
SW Release : 22년01월06일 배포(AX 22년01월10일 배포)

**재현 순서** 
#1번 케이스
1. http://192.168.0.56:8000 웹페이지 접속
2. 왼쪽 메뉴 리스트에서 Stream 메뉴 클릭
3. 설정할 MX의 왼쪽 + 버튼 클릭
4. 설정할 스트림의 오른쪽 Add chain 버튼 클릭
5. Vision App 항목에서 적용할 플러그인 선택
6. Analytics 항목에서 적용할 모델 선택 시 NO DATA FOUND 메세지가 발생하며 선택 불가

#2번 케이스
1. http://192.168.0.56:8000 웹페이지 접속
2. 왼쪽 메뉴 리스트에서 Setting 메뉴 클릭
3. Setting 화면에서 System or User 메뉴 클릭
4. 왼쪽 메뉴 리스트에서 Stream 메뉴 클릭
5. 설정할 MX의 왼쪽 + 버튼 클릭
6. 설정할 스트림의 오른쪽 Add chain 버튼 클릭
7. Vision App 항목에서 적용할 플러그인 선택
8. Analytics 항목에서 적용할 모델 선택 시 NO DATA FOUND 메세지가 발생하며 선택 불가

#3번 케이스
1. http://192.168.0.56:8000 웹페이지 접속
2. 왼쪽 메뉴 리스트에서 DX or Model 메뉴 클릭
3. 왼쪽 메뉴 리스트에서 Stream 메뉴 클릭
4. 설정할 MX의 왼쪽 + 버튼 클릭
5. 설정할 스트림의 오른쪽 Add chain 버튼 클릭
6. Vision App 항목에서 적용할 플러그인 선택
7. Analytics 항목에서 적용할 모델 선택 시 모델 선택 가능
8. DX 항목에서 적용할 DX 선택
9. CONFIRM 버튼 클릭

**예상 결과**
DX 상세 정보 페이지에서 새로고침 작업 시 DX 상세 정보를 표출할 수 있다

**실제 결과** 
#1번 케이스
웹페이지 접속 후 Stream 메뉴 → MX의 왼쪽 + 버튼 → Add chain → Vision App → Analytics에서 모델 선택 시 NO DATA FOUND 메세지가 발생하며 선택 불가

#2번 케이스
웹페이지 접속 후 Setting의 System or User 메뉴 → Stream 메뉴 → MX의 왼쪽 + 버튼 → Add chain → Vision App → Analytics에서 모델 선택 시 NO DATA FOUND 메세지가 발생하며 선택 불가

#3번 케이스
웹페이지 접속 후 DX or Model 메뉴 → Stream 메뉴 → MX의 왼쪽 + 버튼 → Add chain → Vision App(모델 선택 가능) → DX → CONFIRM

**빈도**
Always

**심각도**
Critical

**추가 설명 / 스크린샷 / 동영상** 
#1번 케이스
![Analytics에서 모델 선택 시 NO DATA FOUND 메세지가 발생하며 선택 불가1-1](https://user-images.githubusercontent.com/93699320/149736590-1e997712-3755-4068-9ae1-36b0d154b0e5.png)
![Analytics에서 모델 선택 시 NO DATA FOUND 메세지가 발생하며 선택 불가1-2](https://user-images.githubusercontent.com/93699320/149736594-b9f922e5-0568-42cd-8997-70db5b157b50.png)

#2번 케이스
![Analytics에서 모델 선택 시 NO DATA FOUND 메세지가 발생하며 선택 불가2-1](https://user-images.githubusercontent.com/93699320/149736596-929fe8f4-2048-4d75-8704-d836317e4844.png)
![Analytics에서 모델 선택 시 NO DATA FOUND 메세지가 발생하며 선택 불가2-2(1)](https://user-images.githubusercontent.com/93699320/149736600-da86df51-8c95-4c2b-b477-9f5494b15f9b.png)
![Analytics에서 모델 선택 시 NO DATA FOUND 메세지가 발생하며 선택 불가2-2(2)](https://user-images.githubusercontent.com/93699320/149736602-f6bcea6a-2425-4fc5-8ed5-43114f36aebc.png)
![Analytics에서 모델 선택 시 NO DATA FOUND 메세지가 발생하며 선택 불가2-3](https://user-images.githubusercontent.com/93699320/149736605-3ee3de9d-6c56-4d16-a914-da0877ecea12.png)

#3번 케이스
![Analytics에서 모델 선택 시 선택 가능3-1](https://user-images.githubusercontent.com/93699320/149736607-6f6bcaa8-e9ce-4206-aee3-4fea1afa3354.png)
![Analytics에서 모델 선택 시 선택 가능3-2(1)](https://user-images.githubusercontent.com/93699320/149736609-cf7de6c9-3718-49c8-a4d2-06c0c65d88cc.png)
![Analytics에서 모델 선택 시 선택 가능3-2(2)](https://user-images.githubusercontent.com/93699320/149736613-52fefc23-5947-4bd3-a64a-333d479763e0.png)
![Analytics에서 모델 선택 시 선택 가능3-3](https://user-images.githubusercontent.com/93699320/149736615-7bab88b4-1b5a-4f0e-9db2-934e948f5503.png)

**Comment by jaypark-snuailab** [comment]
1. 우선 말씀드릴 것은 AX의ᅟ 경우 *-devel 버전은 개발자 테스트용 빌드로서 검증 배포용이 아님을 양지바랍니다. 
2. 지금 올려주신 이슈는 개발자 테스트용 빌드에서 발생하는 문제입니다.
3. 따라서 이슈는 invaild 처리하겠습니다.

**Comment by jaypark-snuailab** [comment]
- Model File Upload시 실제 파일 유무를 확인하는 코드에서 오류발생하여 모델 Deploy on DX 기능에 문제 발생.
- 1/21 릴리즈에 반영 예정.
