### ISSUE TITLE
신규 릴리즈 버전(0.2-22.1.21) 설치 후 DX offline으로 변경

### ISSUE THREAD

**Issue by TaeHoon-SNU** [snuailab/autocare_issue_reporter#55]
문제점 요약
신규 릴리즈 버전(0.2-22.1.21) 설치 후 DX offline으로 변경

실행 환경
운영 체제 : Ubuntu 20.04
SW Release : 22년01월21일 배포

재현 순서
 - 초기 정보 입력 -
1. http://{IP address}:8000 웹페이지 접속
2. 시스템 정보 입력 후 NEXT 버튼 클릭
3. 관리자 정보 입력 후 NEXT 버튼 클릭
4. 입력 정보 확인 후  UPDATE 버튼 클릭

 - Model 등록 -
1. http://{IP address}:8000 웹페이지 접속
2. 왼쪽 메뉴 리스트에서 Model 메뉴 클릭
3. 오른쪽 상단 NEW MODEL 클릭
4. 등록할 모델의 정보(NAME, Desc, Capacity, ID) 입력
5. 업로드할 모델 파일 선택
6. YES 클릭

 - DX 추가 -
1. http://{IP address}:8000 웹페이지 접속
2. 왼쪽 메뉴 리스트에서 DX 메뉴 클릭
3. 오른쪽 상단 Discover 클릭
4. 추가할 DX에서 ADD DX 버튼 클릭
5. CLOSE 버튼 클릭

 - Model 다운로드 -
1. http://{IP address}:8000 웹페이지 접속
2. 왼쪽 메뉴 리스트에서 DX 메뉴 클릭
3. Downloaded Models 항목에서 + 버튼 클릭 
4. 다운로드할 모델 선택

예상 결과
DX에 Model 다운로드 후 DX가 Online 상태로 유지되고 동작되어야 한다

실제 결과
DX에 Model 다운로드 후 DX가 offline 상태(약 1분 이후)로 변경

빈도
Always

심각도
Critical

추가 설명 / 스크린샷 / 동영상
[신규 릴리즈 버전(0.2-22.1.21) 설치 후 DX offline으로 변경.zip](https://github.com/snuailab/autocare_issue_reporter/files/7922401/0.2-22.1.21.DX.offline.zip)
![K-011](https://user-images.githubusercontent.com/93699320/150717073-d1d49169-cd02-4254-9716-45897f3c561f.png)
![K-012](https://user-images.githubusercontent.com/93699320/150717077-c971a095-461b-43ab-a917-718da31c0711.png)

**Comment by jaypark-snuailab** [comment]
@jaeminjeon-snuailab AX 로그를 보니 모델 다운로드 이후 alive message가 제대로 수신되지 않는 것 갈습니다. 기술팀에서 사용한 모델 확인하여 모델 문제인지 아닌지 확인 바랍니다.

**Comment by jaeminjeon-snuailab** [comment]
@TaeHoon-SNU 혹시 테스트 시에 제가 release note 에 올려놓은 모델을 사용하셨나요? 어떤 모델을 사용하셨는지 확인이 필요할 거 같습니다.

**Comment by TaeHoon-SNU** [comment]
릴리즈 노트에 올려주신 모델로 했습니다.

**Comment by jaeminjeon-snuailab** [comment]
혹시 테스트 하는 PC의 GPU가 어떤건지 알 수 있을까요?

**Comment by TaeHoon-SNU** [comment]
![image](https://user-images.githubusercontent.com/93699320/150735809-b8bed954-ec8c-4b7b-b2bb-bfa917e6937e.png)
설치된 GPU입니다.

**Comment by TaeHoon-SNU** [comment]
![image](https://user-images.githubusercontent.com/93699320/150736273-5a6b17f8-fb1d-400e-9dbd-5e638f3c89cb.png)
테스트하는 Model info입니다.

**Comment by jaeminjeon-snuailab** [comment]
해당 이슈는 모델 호환성 관련 문제로 RTX 2080 SUPER 에서는 정상적으로 동작하는 모델이 RTX 3070 에서는 호환성 문제로 정상동작하지 않아서 발생하는 문제로 파악됩니다. 해당 이슈 관련하여 3070 에서 정상 동작할 수 있는 모델을 찾아서 전달하도록 하겠습니다.

**Comment by TaeHoon-SNU** [comment]
계속 동일한 H/W에 동일한 model로 테스트를 했는데 Model쪽에 변경된 내용이 많은 건가요?
현재 동일한 H/W에 0.2-22.1.6 버전으로 테스트하는 서버는 객체 검출이 되고 있습니다.

**Comment by jaeminjeon-snuailab** [comment]
DX 에서 사용하는 Deepstream  버전이 5.0 에서 6.0 으로 업그레이드되면서 실행 환경에 대한 영향이 있습니다. 모델이나 nvidia driver 버전의 변경이 필요할 것 같아서 지금 확인중에 있습니다.

**Comment by jaeminjeon-snuailab** [comment]
테스트 결과 nvidia driver 버전 문제로 인한 이슈로 확인됩니다. deepstream 6.0 에서는 nvidia driver 버전 470 으로 nvidia driver 버전 변경이 필요합니다. 아래의 문서를 참고하여 버전 변경 후 테스트 부탁드리겠습니다.
- https://www.notion.so/snuailab/nvidia-driver-470-108ae2e406474fbab6f70cdf9c95b97d

**Comment by xroger88** [comment]
전재민님, 문제점 찾느라 수고 많았습니다. NVIDIA 드라이버 버전의 경우 향후에도 문제가 될 소지가 있으므로, 이번에 DX 모델 Info에 호환가능한 드라이버 버전을 프로퍼티를 추가하고, DX에서 로딩시 호환가능한 드라이버 버전을 채크하는 로직을 추가하면 어떨까합니다. 버전에 호환가능한 버전이 탑재되어 있지 않으면 에러를 로그로 남기면 어떨까 합니다. 다음 버전에 장기적으로 생각해 보시기 바랍니다.

**Comment by jaypark-snuailab** [comment]
본인 환경도 GeFroce 3070 + Deriver 460 버전이었고 동일 문제 발생하였는데 드라이버 470으로 업그레이드 후 정상 동작 확인했습니다.

**Comment by jaeminjeon-snuailab** [comment]
해당 이슈는 deepstream 버전 업그레이드에 따른 nvidia driver 버전 문제로 resolve 처리 하겠습니다.
