### ISSUE TITLE
DX 종료에 대한 경고 메시지 미발생

### ISSUE THREAD

**Issue by TaeHoon-SNU** [snuailab/autocare_issue_reporter#6]
[Pre-condition & Test Data]
웹페이지 실행 http://{IP address}:8000/frontend/console/
[Environment]
Ubuntu 20.04, autocare_docker S/W Version : 11/04 배포 S/W
[Steps to reproduce]
왼쪽 메뉴 리스트에서 Dxs 메뉴 클릭 → 제어할 DX의 종료 버튼 클릭
[Expect result]
제어할 DX의 inference가 종료되어야 한다
[Actual result]
DX 종료에 대한 경고 메시지 미발생(시스템에 영향을 받는 작업 시 경고 메세지 표출 필수)
[Frequency]
Allway
[Severity/Priority]
Critical

**Comment by sangb-han** [comment]
### 문제 분류 
 * Enhancement (문제 아님) 

### 해결 방법 
 * 신규 신규 UI(WebApp)로 개선시 반영 예정
   * 현재 UI에서는 기능 추가/개선이 없으며, 명백한 에러만 수정 예정입니다.
