### ISSUE TITLE
MX(DX) 종료 후 재실행 시 분석 이벤트 검출 불가로 확인 불가

### ISSUE THREAD

**Issue by TaeHoon-SNU** [snuailab/autocare_issue_reporter#7]
[Pre-condition & Test Data]
웹페이지 http://{IP address}:8000/frontend/console/와 MX-Client(VIVEex) 실행
[Environment]
Mx-Client(VIVEex) Version: 4.2.0.32843, Ubuntu 20.04, autocare_docker S/W Version : 11/04 배포 S/W
[Steps to reproduce]
MX-Client(VIVEex) 실행/AX 시스템 접속
 [Expect result]
MX(DX) 종료 후 재실행 시 분석 이벤트 검출이 확인되어야 한다
[Actual result]
MX(DX) 종료 후 재실행 시 분석 이벤트 검출 불가로 확인 불가
 → 전체 시스템 설치 및 설정 후 MX에서 최초 1회만 분석 이벤트 검출 확인 가능
[Frequency]
Allway
[Severity/Priority]
Critical

**Comment by snuailab-jinholee** [comment]
금요일 USB 버전에서 수정 완료하였습니다.
fix in dx@0.1-21.11.5-devel version
