### ISSUE TITLE
분석 이벤트 검출 불가로 MX의 분석 이벤트 관련 기능 확인 불가

### ISSUE THREAD

**Issue by TaeHoon-SNU** [snuailab/autocare_issue_reporter#8]
[Pre-condition & Test Data]
MX-Client(VIVEex)
[Environment]
Mx-Client(VIVEex) Version: 4.2.0.32843, Ubuntu 20.04, autocare_docker S/W Version : 11/04 배포 S/W
[Steps to reproduce]
리소스 트리 패널의 카메라에서 마우스 오른쪽 버튼 클릭 후 카메라 설정 선택 → 카메라 설정 창에서 플러그인 탭 클릭 → 사용할 플러그인 활성화 후 적용 클릭
[Expect result]
플러그인이 활성화 후 분석 이벤트가 검출되고 분석 이벤트가 표출되어야 한다
[Actual result]
분석 이벤트 검출 불가로 MX의 분석 이벤트 관련 기능 확인 불가
 → 상세 설명,이벤트 알림,ROI 이벤트,ROC 이벤트,객체 표출,알림 이벤트,즐겨찾기(북마크) 이벤트 등
[Frequency]
Allway
[Severity/Priority]
Critical

**Comment by jeongho2** [comment]
플러그인이 활성화 된 후 분석 결과가 표시 안되는 경우는 1.Ax에게 해당 Stream에 Dx를 할당 받지 못한 경우(Dx의 Capacity가 없는 경우, 플러그인에서 사용하는 App의 model을 가진 Dx가 없는 경우) 2. Dx가 Inference가 Delayed되고 있는 경우 가 있습니다.
1번 같은 case는 Nx Client에서 Stream Assgined Failed 라는 일반 이벤트 알림이 뜹니다. 2번과 같은 case는 아직 Dx가 Inference를 시작하지 않은 경우이므로 Inference 결과인 Anayltics Stream을 받지 못했기 때문이라서 기다려야합니다. 길게는 1분 정도 시간이 소요됩니다.

**Comment by jeongho2** [comment]
추가적으로 이벤트와 같은 용어에 대한 구분이 필요할 것 같습니다. event, feature, stream 등의 용어가 혼재되어 사용중이라 이에 대한 정리가 필요합니다. 해당 내용은 문서로 정리하여 공유드리겠습니다.

**Comment by mingeolyoo** [comment]
[Pre-condition & Test Data]
MX-Client(VIVEex)
[Environment]
Mx-Client(VIVEex) Version: 4.2.0.32843, Ubuntu 20.04, autocare_docker S/W Version : '3.9'
[Steps to reproduce]
MX-Client 접속 -> 시스템 관리 -> 이벤트 규칙(일반이벤트 및 분석이벤트 설정) -> 영상 분석할 카메라 우클릭 ->
카메라 설정 -> 해당 플러그인 활성화 적용 -> 영상 분석할 카메라 우클릭 ->아이템 표시(객체) 활성화
[Expect result]
플러그인이 활성화 및 DX 활성화 후 객체 검출이 가능해야 한다.
[Actual result]
DX 배포는 확인 할 수 있지만 MX Client에서 영상에 대한 객체 검출 불가
[Frequency]
Allway
[Severity/Priority]
Critica
![ax dxs](https://user-images.githubusercontent.com/93703111/141749209-b3d98a61-41a1-42e0-aa7a-2c027add6cec.JPG)
![ax stream](https://user-images.githubusercontent.com/93703111/141749213-e1efb767-9c4e-4438-8063-3cd09bb7a78e.JPG)
[dx.log](https://github.com/snuailab/autocare_issue_reporter/files/7537143/dx.log)
![mxclient](https://user-images.githubusercontent.com/93703111/141749225-080e7a0f-8db7-4dcf-9349-bf3d579ca0a0.JPG)

**Comment by jaeminjeon-snuailab** [comment]
@mingeolyoo 해당 이슈의 로그도 같이 첨부 부탁드리겠습니다.

**Comment by mingeolyoo** [comment]
@jaeminjeon-snuailab 로그 첨부되어있습니다
![log](https://user-images.githubusercontent.com/93703111/141875240-18cf3604-92cf-496b-8704-458fcdb0d097.JPG)
.

**Comment by jaeminjeon-snuailab** [comment]
금일 김태훈 팀장님 PC에서 확인한 로그 내용입니다.
[dx.log](https://github.com/snuailab/autocare_issue_reporter/files/7551151/dx.log)
[gst.log](https://github.com/snuailab/autocare_issue_reporter/files/7551152/gst.log)

**Comment by jaeminjeon-snuailab** [comment]
해당 이슈는 윈도우상에서 가상환경으로 리눅스를 구동할 때 nvidia 환경설정과 TRT 엔진 빌드 관련된 이슈라서 윤진 팀장님 @jinyoon82 을 태그하였습니다. 확인 부탁 드리겠습니다.

**Comment by TaeHoon-SNU** [comment]
금일 테스트는 가상환경에서 리눅스를 구동하는게 아니라 HP 워크스테이션에 직접 우분투 20.04.2 버전을 설치하고 진행하고 있습니다.

**Comment by jaeminjeon-snuailab** [comment]
그렇다면 엔진 빌드 관련해서만 확인하면 될 거 같습니다.
아래 gst.log가 금일 확인한 로그인데, 해당 로그에서 engine 관련하여 에러가 발생했는데, 윤진팀장님께서 한번 확인해주시면 될 거 같습니다.
- [gst.log](https://github.com/snuailab/autocare_issue_reporter/files/7552239/gst.log)

**Comment by TaeHoon-SNU** [comment]
Vehicle Detect 모델 압축 파일(vd.zip) 내부의 model.info 정보가 달라서 발생한 문제입니다.
vd.zip 파일명이 변경이 없어 기존에 받았던 vd.zip 파일로 모델을 등록하여 테스트를 진행하였습니다.
USB로 새로 받은 vd.zip 파일로 모델을 등록하여 테스트 시 분석 이벤트 검출이 정상적으로 됩니
![분석 이벤트 검출 오류 관련 - vd zip 내 model info의 tracker 내용 변경](https://user-images.githubusercontent.com/93699320/142158053-fe9886be-e7d4-454d-9e2a-c7f8ff29ac46.png)
다.

**Comment by jaeminjeon-snuailab** [comment]
그러면 해당 이슈는 close 해도 될까요?

**Comment by TaeHoon-SNU** [comment]
넵!
분석 이벤트 검출은 확인되었습니다.
세부적인 분석 이벤트 관련 기능은 별도로 추가하도록 하겠습니다.

**Comment by jaeminjeon-snuailab** [comment]
넵 감사합니다. 이 이슈는 close 하겠습니다.
