### ISSUE TITLE
웹페이지 로그인/시스템 설정/로그 관련 기능 추가 필요

### ISSUE THREAD

**Issue by TaeHoon-SNU** [snuailab/autocare_issue_reporter#9]
[Pre-condition & Test Data]
웹페이지 실행 http://{IP address}:8000/frontend/console/
[Environment]
Mx-Client(VIVEex) Version: 4.2.0.32843, Ubuntu 20.04, autocare_docker S/W Version : 11/04 배포 S/W
[Steps to reproduce]
AX 시스템 접속
[Expect result]
웹페이지 로그인/시스템 설정/로그 관련 기능 확인되어야 한다
[Actual result]
웹페이지 로그인/시스템 설정/로그 관련 기능 확인 불가
[Frequency]
Allway
[Severity/Priority]
Critical

**Comment by sangb-han** [comment]
신규 UI(WebApp)로 개선시 반영 예정
  - 현재 UI에서는 기능 추가/개선이 없으며, 명백한 에러만 수정 예정입니다.
